<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sys\db\admin;

use \php\_Boot\HxAnon;
use \php\Boot;
use \haxe\CallStack;
use \sys\db\admin\_Serialized\Errors;
use \php\_Boot\HxString;
use \haxe\ds\StringMap;
use \php\_Boot\HxException;

class Serialized {
	/**
	 * @var string
	 */
	static public $BASE64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%:";
	/**
	 * @var string
	 */
	static public $IDENT = "  ";
	/**
	 * @var \EReg
	 */
	static public $clname;
	/**
	 * @var \EReg
	 */
	static public $ident;

	/**
	 * @var \StringBuf
	 */
	public $buf;
	/**
	 * @var object
	 */
	public $cur;
	/**
	 * @var int
	 */
	public $pos;
	/**
	 * @var \Array_hx
	 */
	public $scache;
	/**
	 * @var int
	 */
	public $scount;
	/**
	 * @var StringMap
	 */
	public $shash;
	/**
	 * @var int
	 */
	public $tabs;
	/**
	 * @var bool
	 */
	public $useEnumIndex;
	/**
	 * @var string
	 */
	public $value;

	/**
	 * @param string $v
	 * 
	 * @return void
	 */
	public function __construct ($v) {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:62: characters 3-17
		$this->value = $v;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:63: characters 3-10
		$this->pos = 0;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:64: characters 3-11
		$this->tabs = 0;
	}

	/**
	 * @param string $end
	 * @param string $postfix
	 * 
	 * @return void
	 */
	public function close ($end, $postfix = null) {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:721: characters 3-16
		$this->buf = $this->cur->buf;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:722: characters 3-16
		$t = "\x0A";
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:723: lines 723-724
		$_g = 0;
		$_g1 = $this->tabs - 1;
		while ($_g < $_g1) {
			$i = $_g++;
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:724: characters 4-14
			$t = ($t??'null') . (Serialized::$IDENT??'null');
		}

		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:725: lines 725-742
		if (((mb_strlen($t) + $this->cur->totalSize) > 80) && ($this->cur->maxSize > 10)) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:726: characters 4-21
			$first = true;
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:727: lines 727-730
			$_g2 = 0;
			$_g3 = $this->cur->lines;
			while ($_g2 < $_g3->length) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:727: characters 9-13
				$line = ($_g3->arr[$_g2] ?? null);
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:727: lines 727-730
				++$_g2;
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:728: characters 5-52
				if ($first) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:728: characters 17-30
					$first = false;
				} else {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:728: characters 36-52
					$this->buf->add($this->cur->sep);
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:729: characters 5-30
				$this->buf->add(($t??'null') . (Serialized::$IDENT??'null') . ($line??'null'));
			}

			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:731: characters 4-14
			$this->buf->add($t);
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:732: characters 4-16
			$this->buf->add($end);
		} else {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:734: characters 4-72
			if (($this->cur->prefix !== null) && ($this->cur->lines->length > 0)) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:734: characters 53-72
				$this->buf->add($this->cur->prefix);
			}
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:735: characters 4-21
			$first1 = true;
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:736: lines 736-739
			$_g21 = 0;
			$_g31 = $this->cur->lines;
			while ($_g21 < $_g31->length) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:736: characters 9-13
				$line1 = ($_g31->arr[$_g21] ?? null);
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:736: lines 736-739
				++$_g21;
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:737: characters 5-52
				if ($first1) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:737: characters 17-30
					$first1 = false;
				} else {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:737: characters 36-52
					$this->buf->add($this->cur->sep);
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:738: characters 5-18
				$this->buf->add($line1);
			}

			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:740: characters 4-52
			if (!$first1 && ($postfix !== null)) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:740: characters 36-52
				$this->buf->add($postfix);
			}
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:741: characters 4-16
			$this->buf->add($end);
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:743: characters 3-16
		$this->cur = $this->cur->old;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:744: characters 3-9
		$this->tabs--;
	}

	/**
	 * @return string
	 */
	public function encode () {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:69: characters 3-8
		throw new HxException("You can't edit this without -lib hscript");
	}

	/**
	 * @return string
	 */
	public function escape () {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:457: lines 457-458
		if ($this->value === "") {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:458: characters 4-20
			return "empty()";
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:459: characters 3-24
		$this->buf = new \StringBuf();
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:460: characters 3-23
		$this->scache = new \Array_hx();
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:461: characters 3-42
		try {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:461: characters 7-13
			$this->loop();
		} catch (\Throwable $__hx__caught_e) {
			CallStack::saveExceptionTrace($__hx__caught_e);
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			if ($__hx__real_e instanceof Errors) {
				$e = $__hx__real_e;
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:461: characters 34-42
				$this->pos = -1;
			} else  throw $__hx__caught_e;
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:462: lines 462-463
		if ($this->pos !== mb_strlen($this->value)) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:463: characters 4-42
			return "invalid(" . ($this->quote($this->value)??'null') . ")";
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:464: characters 3-28
		$str = $this->buf->b;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:465: lines 465-466
		if ($this->useEnumIndex) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:466: characters 4-32
			$str = "indexes(" . ($str??'null') . ")";
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:467: characters 3-13
		return $str;
	}

	/**
	 * @param int $pos
	 * 
	 * @return int
	 */
	public function get ($pos) {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:471: characters 3-31
		return HxString::charCodeAt($this->value, $pos);
	}

	/**
	 * @return void
	 */
	public function loop () {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:500: characters 11-21
		$_g = HxString::charCodeAt($this->value, $this->pos++);
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:500: lines 500-664
		if ($_g === null) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:664: characters 4-9
			throw new HxException(Errors::Invalid());
		} else {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:500: characters 11-21
			if ($_g === 67) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:652: characters 4-28
				$this->open("new custom(", ", ");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:653: characters 4-40
				$this->buf->add($this->quote($this->readString(), Serialized::$clname));
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:654: characters 4-10
				$this->next();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:655: lines 655-658
				while (HxString::charCodeAt($this->value, $this->pos) !== 103) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:656: characters 5-11
					$this->loop();
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:657: characters 5-11
					$this->next();
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:659: characters 4-14
				$this->close(")");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:660: characters 4-9
				$this->pos++;
			} else if ($_g === 82 || $_g === 121) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:549: characters 4-9
				$this->pos--;
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:550: characters 4-32
				$this->buf->add($this->quote($this->readString()));
			} else if ($_g === 97) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:529: characters 4-18
				$this->open("[", ", ");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:530: lines 530-546
				while (true) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:531: characters 6-23
					$c = HxString::charCodeAt($this->value, $this->pos);
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:532: lines 532-535
					if ($c === 104) {
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:533: characters 6-11
						$this->pos++;
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:534: characters 7-12
						break;
					}
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:536: lines 536-544
					if ($c === 117) {
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:537: characters 6-11
						$this->pos++;
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:538: lines 538-541
						$_g1 = 0;
						$_g11 = $this->readDigits() - 1;
						while ($_g1 < $_g11) {
							$i = $_g1++;
							#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:539: characters 7-22
							$this->buf->add("null");
							#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:540: characters 7-13
							$this->next();
						}

						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:542: characters 6-21
						$this->buf->add("null");
					} else {
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:544: characters 6-12
						$this->loop();
					}
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:545: characters 5-11
					$this->next();
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:547: characters 4-14
				$this->close("]");
			} else if ($_g === 98) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:571: characters 4-20
				$this->buf->add("hash(");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:572: characters 4-21
				$this->loopObj(104);
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:573: characters 4-16
				$this->buf->add(")");
			} else if ($_g === 99) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:640: characters 4-19
				$this->buf->add("new ");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:641: characters 4-26
				$cl = $this->readString();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:642: lines 642-648
				if (Serialized::$clname->match($cl)) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:643: characters 5-22
					$this->buf->add(($cl??'null') . "(");
				} else {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:645: characters 5-22
					$this->buf->add("class(");
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:646: characters 5-23
					$this->buf->add($this->quote($cl));
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:647: characters 5-17
					$this->buf->add(",");
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:649: characters 4-21
				$this->loopObj(103);
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:650: characters 4-16
				$this->buf->add(")");
			} else if ($_g === 100) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:518: characters 5-18
				$p1 = $this->pos;
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:519: lines 519-526
				while (true) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:520: characters 6-23
					$c1 = HxString::charCodeAt($this->value, $this->pos);
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:522: lines 522-525
					if ((($c1 >= 43) && ($c1 < 58)) || ($c1 === 101) || ($c1 === 69)) {
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:523: characters 7-12
						$this->pos++;
					} else {
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:525: characters 7-12
						break;
					}
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:527: characters 5-40
				$this->buf->add(mb_substr($this->value, $p1, $this->pos - $p1));
			} else if ($_g === 102) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:510: characters 4-18
				$this->buf->add(false);
			} else if ($_g === 105) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:504: characters 4-25
				$this->buf->add($this->readDigits());
			} else if ($_g === 106) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:616: characters 4-26
				$cl1 = $this->readString();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:617: characters 4-30
				$this->buf->add($this->quote($cl1, Serialized::$clname));
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:618: lines 618-619
				if (HxString::charCodeAt($this->value, $this->pos++) !== 58) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:619: characters 5-10
					throw new HxException(Errors::Invalid());
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:620: characters 4-29
				$index = $this->readDigits();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:621: characters 4-33
				$e = \Type::resolveEnum($cl1);
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:622: lines 622-627
				if ($e === null) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:623: characters 5-27
					$this->buf->add("[" . ($index??'null') . "]");
				} else {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:625: characters 5-24
					$this->useEnumIndex = true;
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:626: characters 5-50
					$this->buf->add("." . ((\Type::getEnumConstructs($e)->arr[$index] ?? null)??'null'));
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:628: lines 628-629
				if (HxString::charCodeAt($this->value, $this->pos++) !== 58) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:629: characters 5-10
					throw new HxException(Errors::Invalid());
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:630: characters 4-29
				$nargs = $this->readDigits();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:631: lines 631-638
				if ($nargs > 0) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:632: characters 5-17
					$this->buf->add("(");
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:633: lines 633-636
					$_g2 = 0;
					$_g12 = $nargs;
					while ($_g2 < $_g12) {
						$i1 = $_g2++;
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:634: characters 6-31
						if ($i1 > 0) {
							#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:634: characters 18-31
							$this->buf->add(", ");
						}
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:635: characters 6-12
						$this->loop();
					}

					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:637: characters 5-17
					$this->buf->add(")");
				}
			} else if ($_g === 107) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:512: characters 4-18
				$this->buf->add("NaN");
			} else if ($_g === 108) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:552: characters 4-22
				$this->open("list(", ", ");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:553: lines 553-556
				while (HxString::charCodeAt($this->value, $this->pos) !== 104) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:554: characters 5-11
					$this->loop();
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:555: characters 5-11
					$this->next();
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:557: characters 4-14
				$this->close(")");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:558: characters 4-9
				$this->pos++;
			} else if ($_g === 109) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:516: characters 4-21
				$this->buf->add("NegInf");
			} else if ($_g === 110) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:502: characters 4-17
				$this->buf->add(null);
			} else if ($_g === 111) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:569: characters 4-21
				$this->loopObj(103);
			} else if ($_g === 112) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:514: characters 4-18
				$this->buf->add("Inf");
			} else if ($_g === 113) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:575: characters 4-23
				$this->buf->add("inthash(");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:576: characters 4-22
				$this->open("{", ", ", " ");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:577: characters 4-23
				$c2 = HxString::charCodeAt($this->value, $this->pos++);
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:578: lines 578-584
				while ($c2 === 58) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:579: characters 5-34
					$this->buf->add("'" . ($this->readDigits()??'null') . "'");
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:580: characters 5-19
					$this->buf->add(" : ");
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:581: characters 5-11
					$this->loop();
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:582: characters 9-19
					$c2 = HxString::charCodeAt($this->value, $this->pos++);
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:583: characters 5-11
					$this->next();
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:585: lines 585-586
				if ($c2 !== 104) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:586: characters 5-10
					throw new HxException(Errors::Invalid());
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:587: characters 4-19
				$this->close("}", " ");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:588: characters 4-16
				$this->buf->add(")");
			} else if ($_g === 114) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:662: characters 4-36
				$this->buf->add("ref(" . ($this->readDigits()??'null') . ")");
			} else if ($_g === 115) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:590: characters 5-28
				$len = $this->readDigits();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:591: lines 591-592
				if ((HxString::charCodeAt($this->value, $this->pos++) !== 58) || ((mb_strlen($this->value) - $this->pos) < $len)) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:592: characters 5-10
					throw new HxException(Errors::Invalid());
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:593: characters 4-21
				$this->buf->add("bytes(");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:594: characters 4-42
				$this->buf->add($this->quote(mb_substr($this->value, $this->pos, $len)));
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:595: characters 4-16
				$this->buf->add(")");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:596: characters 4-14
				$this->pos += $len;
			} else if ($_g === 116) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:508: characters 4-17
				$this->buf->add(true);
			} else if ($_g === 118) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:560: characters 4-20
				$this->buf->add("date(");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:561: characters 4-41
				$this->buf->add($this->quote(mb_substr($this->value, $this->pos, 19)));
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:562: characters 4-16
				$this->buf->add(")");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:563: characters 4-13
				$this->pos += 19;
			} else if ($_g === 119) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:598: characters 4-40
				$this->buf->add($this->quote($this->readString(), Serialized::$clname));
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:599: characters 4-30
				$constr = $this->readString();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:600: lines 600-603
				if (Serialized::$ident->match($constr)) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:601: characters 5-26
					$this->buf->add("." . ($constr??'null'));
				} else {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:603: characters 5-35
					$this->buf->add("[" . ($this->quote($constr)??'null') . "]");
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:604: lines 604-605
				if (HxString::charCodeAt($this->value, $this->pos++) !== 58) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:605: characters 5-10
					throw new HxException(Errors::Invalid());
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:606: characters 4-29
				$nargs1 = $this->readDigits();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:607: lines 607-614
				if ($nargs1 > 0) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:608: characters 5-17
					$this->buf->add("(");
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:609: lines 609-612
					$_g3 = 0;
					$_g13 = $nargs1;
					while ($_g3 < $_g13) {
						$i2 = $_g3++;
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:610: characters 6-31
						if ($i2 > 0) {
							#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:610: characters 18-31
							$this->buf->add(", ");
						}
						#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:611: characters 6-12
						$this->loop();
					}

					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:613: characters 5-17
					$this->buf->add(")");
				}
			} else if ($_g === 120) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:565: characters 4-21
				$this->buf->add("error(");
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:566: characters 4-10
				$this->loop();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:567: characters 4-16
				$this->buf->add(")");
			} else if ($_g === 122) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:506: characters 4-14
				$this->buf->add(0);
			} else {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:664: characters 4-9
				throw new HxException(Errors::Invalid());
			}
		}
	}

	/**
	 * @param int $eof
	 * 
	 * @return void
	 */
	public function loopObj ($eof) {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:690: characters 3-21
		$this->open("{", ", ", " ");
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:691: lines 691-700
		while (true) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:692: lines 692-693
			if ($this->pos >= mb_strlen($this->value)) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:693: characters 5-10
				throw new HxException(Errors::Invalid());
			}
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:694: lines 694-695
			if (HxString::charCodeAt($this->value, $this->pos) === $eof) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:695: characters 5-10
				break;
			}
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:696: characters 4-39
			$this->buf->add($this->quote($this->readString(), Serialized::$ident));
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:697: characters 4-18
			$this->buf->add(" : ");
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:698: characters 4-10
			$this->loop();
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:699: characters 4-10
			$this->next();
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:701: characters 3-17
		$this->close("}", " ");
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:702: characters 3-8
		$this->pos++;
	}

	/**
	 * @return void
	 */
	public function next () {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:713: characters 3-29
		$line = $this->buf->b;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:714: characters 3-60
		if (mb_strlen($line) > $this->cur->maxSize) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:714: characters 35-60
			$this->cur->maxSize = mb_strlen($line);
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:715: characters 3-31
		$this->cur->totalSize += mb_strlen($line);
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:716: characters 3-23
		$_this = $this->cur->lines;
		$_this->arr[$_this->length] = $line;
		++$_this->length;

		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:717: characters 3-24
		$this->buf = new \StringBuf();
	}

	/**
	 * @param string $str
	 * @param string $sep
	 * @param string $prefix
	 * 
	 * @return void
	 */
	public function open ($str, $sep, $prefix = null) {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:706: characters 3-15
		$this->buf->add($str);
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:707: characters 3-9
		$this->tabs++;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:708: characters 3-101
		$this->cur = new HxAnon([
			"old" => $this->cur,
			"sep" => $sep,
			"prefix" => $prefix,
			"lines" => new \Array_hx(),
			"buf" => $this->buf,
			"totalSize" => 0,
			"maxSize" => 0,
		]);
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:709: characters 3-24
		$this->buf = new \StringBuf();
	}

	/**
	 * @param string $s
	 * @param \EReg $r
	 * 
	 * @return string
	 */
	public function quote ($s, $r = null) {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:451: lines 451-452
		if (($r !== null) && $r->match($s)) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:452: characters 4-12
			return $s;
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:453: characters 3-139
		return "'" . (HxString::split(HxString::split(HxString::split(HxString::split(HxString::split($s, "\\")->join("\\\\"), "'")->join("\\'"), "\x0A")->join("\\n"), "\x0D")->join("\\r"), "\x09")->join("\\t")??'null') . "'";
	}

	/**
	 * @return int
	 */
	public function readDigits () {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:475: characters 4-14
		$k = 0;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:476: characters 4-18
		$s = false;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:477: characters 4-19
		$fpos = $this->pos;
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:478: lines 478-493
		while (true) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:479: characters 5-22
			$c = HxString::charCodeAt($this->value, $this->pos);
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:480: lines 480-481
			if ($c === null) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:481: characters 6-11
				break;
			}
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:482: lines 482-488
			if ($c === 45) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:483: lines 483-484
				if ($this->pos !== $fpos) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:484: characters 7-12
					break;
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:485: characters 6-14
				$s = true;
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:486: characters 6-11
				$this->pos++;
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:487: characters 6-14
				continue;
			}
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:489: lines 489-490
			if (($c < 48) || ($c > 57)) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:490: characters 6-11
				break;
			}
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:491: characters 5-32
			$k = $k * 10 + ($c - 48);
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:492: characters 5-10
			$this->pos++;
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:494: lines 494-495
		if ($s) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:495: characters 5-12
			$k *= -1;
		}
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:496: characters 4-12
		return $k;
	}

	/**
	 * @return string
	 */
	public function readString () {
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:669: characters 11-34
		$_g = HxString::charCodeAt($this->value, $this->pos++);
		#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:669: lines 669-685
		if ($_g === null) {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:685: characters 4-9
			throw new HxException(Errors::Invalid());
		} else {
			#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:669: characters 11-34
			if ($_g === 82) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:680: characters 4-25
				$n = $this->readDigits();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:681: lines 681-682
				if (($n < 0) || ($n >= $this->scache->length)) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:682: characters 5-10
					throw new HxException("Invalid string reference");
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:683: characters 4-20
				return ($this->scache->arr[$n] ?? null);
			} else if ($_g === 121) {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:671: characters 5-28
				$len = $this->readDigits();
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:672: lines 672-673
				if ((HxString::charCodeAt($this->value, $this->pos++) !== 58) || ((mb_strlen($this->value) - $this->pos) < $len)) {
					#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:673: characters 6-11
					throw new HxException(Errors::Invalid());
				}
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:674: characters 4-34
				$s = mb_substr($this->value, $this->pos, $len);
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:675: characters 4-14
				$this->pos += $len;
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:676: characters 4-32
				$s = urldecode($s);
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:677: characters 4-18
				$_this = $this->scache;
				$_this->arr[$_this->length] = $s;
				++$_this->length;

				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:678: characters 4-12
				return $s;
			} else {
				#/home/bubar/projects/spod/src/sys/db/admin/Serialized.hx:685: characters 4-9
				throw new HxException(Errors::Invalid());
			}
		}
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$ident = new \EReg("^[A-Za-z_][A-Za-z0-9_]*\$", "");
		self::$clname = new \EReg("^[A-Za-z_][A-Z.a-z0-9_]*\$", "");
	}
}

Boot::registerClass(Serialized::class, 'sys.db.admin.Serialized');
Serialized::__hx__init();
