<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\form\elements;

use \php\Boot;
use \sugoi\form\FormElement;

class Checkbox extends FormElement {
	/**
	 * @param string $name
	 * @param string $label
	 * @param bool $checked
	 * @param bool $required
	 * @param string $attibutes
	 * 
	 * @return void
	 */
	public function __construct ($name, $label, $checked = false, $required = false, $attibutes = "") {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:10: lines 10-18
		if ($checked === null) {
			$checked = false;
		}
		if ($required === null) {
			$required = false;
		}
		if ($attibutes === null) {
			$attibutes = "";
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:11: characters 3-10
		parent::__construct();
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:13: characters 3-19
		$this->name = $name;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:14: characters 3-21
		$this->label = $label;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:15: characters 3-23
		$this->value = $checked;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:16: characters 3-27
		$this->required = $required;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:17: characters 3-30
		$this->attributes = $attibutes;
	}

	/**
	 * @param string $str
	 * 
	 * @return bool
	 */
	public function getTypedValue ($str) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:32: characters 10-37
		if ($str !== "1") {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:32: characters 24-37
			return $str === "true";
		} else {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:32: characters 10-37
			return true;
		}
	}

	/**
	 * @return bool
	 */
	public function isValid () {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:37: characters 3-17
		$this->errors->clear();
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:38: lines 38-42
		if ($this->required && ($this->value === null)) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:40: characters 4-88
			$this->errors->add("Please check '" . (((($this->label !== null) && ($this->label !== "") ? $this->label : $this->name))??'null') . "'");
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:41: characters 4-16
			return false;
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:43: characters 3-14
		return true;
	}

	/**
	 * @return string
	 */
	public function render () {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:22: characters 3-39
		$n = ($this->parentForm->name??'null') . "_" . ($this->name??'null');
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:24: characters 3-43
		$checkedStr = ($this->value ? "checked" : "");
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Checkbox.hx:26: characters 3-140
		return "<input type=\"checkbox\" id=\"" . ($n??'null') . "\" name=\"" . ($n??'null') . "\" class=\"" . ($this->getClasses()??'null') . "\" value=\"true\" " . ($checkedStr??'null') . " />";
	}
}

Boot::registerClass(Checkbox::class, 'sugoi.form.elements.Checkbox');
