<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\form\elements;

use \php\Boot;
use \php\Web;
use \sugoi\form\FormElement;
use \sugoi\form\Form;

/**
 * Manage flags stored in an Int , various flags are defined by an Enum
 */
class Flags extends FormElement {
	/**
	 * @var \Array_hx
	 */
	public $checked;
	/**
	 * @var int
	 */
	public $columns;
	/**
	 * @var \Array_hx
	 */
	public $data;
	/**
	 * @var bool
	 */
	public $labelLeft;
	/**
	 * @var bool
	 */
	public $labelRight;
	/**
	 * @var string
	 */
	public $selectMessage;
	/**
	 * @var bool
	 */
	public $verticle;

	/**
	 *
	 * @param	name
	 * @param	label
	 * @param	data			list of enums
	 * @param	value			int
	 * @param	?verticle
	 * @param	?labelRight
	 * 
	 * @param string $name
	 * @param string $label
	 * @param \Array_hx $data
	 * @param int $value
	 * @param bool $verticle
	 * @param bool $labelRight
	 * 
	 * @return void
	 */
	public function __construct ($name, $label, $data, $value, $verticle = true, $labelRight = true) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:71: lines 71-89
		if ($verticle === null) {
			$verticle = true;
		}
		if ($labelRight === null) {
			$labelRight = true;
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:72: characters 3-10
		parent::__construct();
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:73: characters 3-19
		$this->name = $name;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:74: characters 3-21
		$this->label = $label;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:75: characters 3-19
		$this->data = $data;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:76: characters 3-21
		$this->value = $value;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:77: characters 3-27
		$this->verticle = $verticle;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:78: characters 3-31
		$this->labelRight = $labelRight;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:79: characters 3-31
		if ($value === null) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:79: characters 22-31
			$value = 0;
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:81: characters 3-15
		$this->checked = new \Array_hx();
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:82: characters 3-13
		$i = 0;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:83: lines 83-86
		$_g = 0;
		while ($_g < $data->length) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:83: characters 8-9
			$f = ($data->arr[$_g] ?? null);
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:83: lines 83-86
			++$_g;
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:84: characters 4-41
			$_this = $this->checked;
			$_this->arr[$_this->length] = ($value & (1 << $i)) !== 0;
			++$_this->length;

			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:85: characters 4-7
			++$i;
		}

		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:88: characters 3-14
		$this->columns = 1;
	}

	/**
	 * @return void
	 */
	public function populate () {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:94: characters 3-61
		$v = Web::getParamValues(($this->parentForm->name??'null') . "_" . ($this->name??'null'));
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:95: characters 3-12
		$this->value = 0;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:97: lines 97-107
		if ($v !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:99: characters 14-44
			$this1 = 0;
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:99: characters 4-45
			$val = $this1;
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:101: lines 101-104
			$_g = 0;
			while ($_g < $v->length) {
				#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:101: characters 9-11
				$vv = ($v->arr[$_g] ?? null);
				#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:101: lines 101-104
				++$_g;
				#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:102: characters 5-56
				$val |= 1 << Boot::dynamicField(\Type::createEnumIndex(Boot::getClass(FakeFlag::class), \Std::parseInt($vv), null), 'index');
			}

			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:106: characters 4-23
			$this->value = $val;
		}
	}

	/**
	 * @return string
	 */
	public function render () {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:119: characters 3-14
		$s = "";
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:120: characters 3-39
		$n = ($this->parentForm->name??'null') . "_" . ($this->name??'null');
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:122: characters 3-29
		$tagCss = $this->getClasses();
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:123: characters 3-36
		$labelCss = $this->getLabelClasses();
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:125: characters 3-13
		$c = 0;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:126: characters 3-34
		$array = \Lambda::array($this->data);
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:127: lines 127-170
		if ($array !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:130: characters 4-58
			$rowsPerColumn = (int)(ceil($array->length / $this->columns));
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:131: characters 4-21
			$s = "<table><tr>";
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:132: lines 132-167
			$_g = 0;
			$_g1 = $this->columns;
			while ($_g < $_g1) {
				$i = $_g++;
				#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:134: characters 5-33
				$s = ($s??'null') . "<td valign=\"top\">\x0A";
				#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:135: characters 5-21
				$s = ($s??'null') . "<table>\x0A";
				#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:137: lines 137-164
				$_g2 = 0;
				$_g11 = $rowsPerColumn;
				while ($_g2 < $_g11) {
					$j = $_g2++;
					#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:139: characters 6-34
					if ($c >= $array->length) {
						#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:139: characters 29-34
						break;
					}
					#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:141: characters 6-17
					$s = ($s??'null') . "<tr>";
					#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:143: characters 6-33
					$row = ($array->arr[$c] ?? null);
					#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:145: characters 6-167
					$checkbox = "<input type=\"checkbox\" class=\"" . ($tagCss??'null') . "\" name=\"" . ($n??'null') . "[]\" id=\"" . ($n??'null') . ($c??'null') . "\" value=\"" . ($c??'null') . "\" " . (((($this->checked->arr[$c] ?? null) ? "checked" : ""))??'null') . " ></input>\x0A";
					#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:148: characters 6-30
					$t = Form::$translator;
					#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:146: characters 6-16
					$label = "<label for=\"" . ($n??'null') . ($c??'null') . "\" class=\"" . "" . "\" > " . ($t->_($row)??'null') . "</label>\x0A";
					#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:153: lines 153-160
					if ($this->labelRight) {
						#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:155: characters 7-72
						$s = ($s??'null') . "<td style='vertical-align:middle;'>" . ($checkbox??'null') . "</td>\x0A";
						#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:156: characters 7-69
						$s = ($s??'null') . "<td style='vertical-align:middle;'>" . ($label??'null') . "</td>\x0A";
					} else {
						#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:158: characters 7-69
						$s = ($s??'null') . "<td style='vertical-align:middle;'>" . ($label??'null') . "</td>\x0A";
						#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:159: characters 7-72
						$s = ($s??'null') . "<td style='vertical-align:middle;'>" . ($checkbox??'null') . "</td>\x0A";
					}
					#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:161: characters 6-18
					$s = ($s??'null') . "</tr>";
					#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:163: characters 6-9
					++$c;
				}

				#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:165: characters 5-20
				$s = ($s??'null') . "</table>";
				#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:166: characters 5-17
				$s = ($s??'null') . "</td>";
			}

			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:168: characters 4-26
			$s = ($s??'null') . "</tr></table>\x0A";
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Flags.hx:172: characters 3-11
		return $s;
	}
}

Boot::registerClass(Flags::class, 'sugoi.form.elements.Flags');
