<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\form\elements;

use \php\Boot;
use \sugoi\form\filters\FloatFilter;

class FloatInput extends Input {
	/**
	 * @param string $name
	 * @param string $label
	 * @param float $value
	 * @param bool $required
	 * 
	 * @return void
	 */
	public function __construct ($name, $label, $value, $required = false) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/FloatInput.hx:8: characters 3-38
		if ($required === null) {
			$required = false;
		}
		parent::__construct($name, $label, $value, $required);
	}

	/**
	 * @param string $str
	 * 
	 * @return float
	 */
	public function getTypedValue ($str) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/FloatInput.hx:13: characters 3-29
		$f = new FloatFilter();
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/FloatInput.hx:14: characters 3-31
		$n = $f->filterString($str);
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/FloatInput.hx:16: lines 16-20
		if (($n === null) && $this->required) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/FloatInput.hx:17: characters 4-14
			return 0.0;
		} else {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/FloatInput.hx:19: characters 4-12
			return $n;
		}
	}
}

Boot::registerClass(FloatInput::class, 'sugoi.form.elements.FloatInput');
