<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\form\elements;

use \php\Boot;

/**
 * ...
 * @author fbarbut
 */
class IntSelect extends Selectbox {
	/**
	 * @param string $name
	 * @param string $label
	 * @param \Array_hx $data
	 * @param int $selected
	 * @param bool $required
	 * @param string $nullMessage
	 * @param string $attributes
	 * 
	 * @return void
	 */
	public function __construct ($name, $label, $data = null, $selected = null, $required = null, $nullMessage = null, $attributes = null) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/IntSelect.hx:7: lines 7-21
		parent::__construct($name, $label, $data, $selected, $required, $nullMessage, $attributes);
	}

	/**
	 * @param string $str
	 * 
	 * @return int
	 */
	public function getTypedValue ($str) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/IntSelect.hx:12: characters 3-47
		if ($str !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/IntSelect.hx:12: characters 20-47
			$str = trim($str);
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/IntSelect.hx:14: lines 14-18
		if (($str === null) || ($str === "")) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/IntSelect.hx:15: characters 4-15
			return null;
		} else {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/IntSelect.hx:17: characters 4-28
			return \Std::parseInt($str);
		}
	}
}

Boot::registerClass(IntSelect::class, 'sugoi.form.elements.IntSelect');
