<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\form\elements;

use \php\Boot;

class StringInput extends Input {
	/**
	 * @param string $name
	 * @param string $label
	 * @param string $value
	 * @param bool $required
	 * @param \Array_hx $validators
	 * @param string $attributes
	 * 
	 * @return void
	 */
	public function __construct ($name, $label, $value = null, $required = null, $validators = null, $attributes = null) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/StringInput.hx:5: lines 5-20
		parent::__construct($name, $label, $value, $required, $validators, $attributes);
	}

	/**
	 * @param string $str
	 * 
	 * @return string
	 */
	public function getTypedValue ($str) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/StringInput.hx:10: lines 10-11
		if ($str !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/StringInput.hx:11: characters 4-31
			$str = trim($str);
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/StringInput.hx:13: lines 13-17
		if (($str === "") || ($str === null)) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/StringInput.hx:14: characters 4-15
			return null;
		} else {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/StringInput.hx:16: characters 4-14
			return $str;
		}
	}
}

Boot::registerClass(StringInput::class, 'sugoi.form.elements.StringInput');
