<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\form\elements;

use \php\Boot;
use \sugoi\form\FormElement;
use \sugoi\form\Form;

class Submit extends FormElement {
	/**
	 * @param string $name
	 * @param string $value
	 * 
	 * @return void
	 */
	public function __construct ($name, $value) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Submit.hx:10: characters 3-10
		parent::__construct();
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Submit.hx:11: characters 3-19
		$this->name = $name;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Submit.hx:12: characters 3-21
		$this->value = $value;
	}

	/**
	 * @return string
	 */
	public function getFullRow () {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Submit.hx:32: characters 3-89
		return "<div class='col-sm-4'></div><div class='col-sm-8'>" . ($this->render()??'null') . "</div>";
	}

	/**
	 * @return bool
	 */
	public function isValid () {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Submit.hx:18: characters 3-14
		return true;
	}

	/**
	 * @return string
	 */
	public function render () {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Submit.hx:23: characters 3-63
		if (Form::$USE_TWITTER_BOOTSTRAP) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/Submit.hx:23: characters 35-63
			$this->cssClass = "btn btn-primary";
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Submit.hx:25: characters 3-198
		$s = "<input type=\"submit\" class=\"" . ($this->getClasses()??'null') . "\" value=\"" . ($this->value??'null') . "\" " . ($this->attributes??'null') . " name=\"" . ($this->parentForm->name??'null') . "_" . ($this->name??'null') . "\" id=\"" . ($this->parentForm->name??'null') . "_" . ($this->name??'null') . "\" />";
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/Submit.hx:26: characters 3-11
		return $s;
	}
}

Boot::registerClass(Submit::class, 'sugoi.form.elements.Submit');
