<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\form\elements;

use \php\Boot;
use \php\_Boot\HxString;

class TextArea extends StringInput {
	/**
	 * @var int
	 */
	public $height;

	/**
	 * @param string $name
	 * @param string $label
	 * @param string $value
	 * @param bool $required
	 * @param \Array_hx $validators
	 * @param string $attributes
	 * 
	 * @return void
	 */
	public function __construct ($name, $label, $value = null, $required = false, $validators = null, $attributes = null) {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:14: characters 3-62
		if ($required === null) {
			$required = false;
		}
		parent::__construct($name, $label, $value, $required, $validators, $attributes);
	}

	/**
	 * @return string
	 */
	public function render () {
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:20: characters 3-39
		$n = ($this->parentForm->name??'null') . "_" . ($this->name??'null');
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:26: lines 26-28
		if ((($this->value === null) || ($this->value === "")) && $this->showLabelAsDefaultValue) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:27: characters 4-17
			$this->value = $this->label;
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:30: characters 3-14
		$s = "";
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:31: characters 3-83
		if ($this->required && $this->parentForm->isSubmitted() && $this->printRequired) {
			#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:31: characters 62-83
			$s = ($s??'null') . "required<br />";
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:33: characters 8-105
		$s1 = "<textarea class=\"" . ($this->getClasses()??'null') . "\" name=\"" . ($n??'null') . "\" id=\"" . ($n??'null') . "\" " . ($this->attributes??'null') . " >";
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:33: characters 108-125
		$s2 = $this->value;
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:33: characters 3-141
		$s = ($s??'null') . ($s1??'null') . ((($s2 === null ? "" : HxString::split(htmlspecialchars(\Std::string($s2), (null ? ENT_QUOTES | ENT_HTML401 : ENT_NOQUOTES)), "\"")->join("&quot;")))??'null') . "</textarea>";
		#/home/bubar/projects/sugoi/src/sugoi/form/elements/TextArea.hx:35: characters 3-11
		return $s;
	}
}

Boot::registerClass(TextArea::class, 'sugoi.form.elements.TextArea');
