<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace tink\core\_Callback;

use \php\Boot;

class SimpleLink implements LinkObject {
	/**
	 * @var \Closure
	 */
	public $f;

	/**
	 * @param \Closure $f
	 * 
	 * @return void
	 */
	public function __construct ($f) {
		#/home/bubar/haxe/haxe_libraries/tink_core/1.21.0/haxelib/src/tink/core/Callback.hx:93: characters 5-15
		$this->f = $f;
	}

	/**
	 * @return void
	 */
	public function cancel () {
		#/home/bubar/haxe/haxe_libraries/tink_core/1.21.0/haxelib/src/tink/core/Callback.hx:96: lines 96-99
		if ($this->f !== null) {
			#/home/bubar/haxe/haxe_libraries/tink_core/1.21.0/haxelib/src/tink/core/Callback.hx:97: characters 7-10
			($this->f)();
			#/home/bubar/haxe/haxe_libraries/tink_core/1.21.0/haxelib/src/tink/core/Callback.hx:98: characters 7-15
			$this->f = null;
		}
	}
}

Boot::registerClass(SimpleLink::class, 'tink.core._Callback.SimpleLink');
