<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace haxe\ds\_Vector;

use \php\Boot;

class PhpVectorData {
	/**
	 * @var mixed
	 */
	public $data;
	/**
	 * @var int
	 */
	public $length;

	/**
	 * @param int $length
	 * 
	 * @return void
	 */
	public function __construct ($length) {
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/haxe/ds/Vector.hx:31: characters 3-23
		$this->length = $length;
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/haxe/ds/Vector.hx:32: characters 10-34
		$this1 = [];
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/haxe/ds/Vector.hx:32: characters 3-34
		$this->data = $this1;
	}
}

Boot::registerClass(PhpVectorData::class, 'haxe.ds._Vector.PhpVectorData');
