<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi;

use \twig\TwigEnvironment;
use \controller\Main;
use \php\_Boot\HxAnon;
use \sys\db\Mysql;
use \php\Boot;
use \sys\db\Connection;
use \haxe\CallStack;
use \sys\db\Manager;
use \sugoi\db\Error;
use \haxe\web\DispatchError;
use \sugoi\db\Variable;
use \php\Web as PhpWeb;
use \haxe\web\Dispatch;
use \sys\db\admin\Admin;
use \php\_Boot\HxString;
use \haxe\ds\StringMap;
use \sys\db\Transaction;
use \php\_Boot\HxException;
use \sugoi\i18n\Locale;
use \db\User;
use \sugoi\db\Session;

class BaseApp {
	/**
	 * @var Config
	 */
	static public $config;

	/**
	 * @var Connection
	 */
	public $cnx;
	/**
	 * @var string
	 */
	public $cookieDomain;
	/**
	 * @var string
	 */
	public $cookieName;
	/**
	 * @var bool
	 */
	public $maintain;
	/**
	 * @var StringMap
	 */
	public $params;
	/**
	 * @var Session
	 */
	public $session;
	/**
	 * @var string
	 */
	public $template;
	/**
	 * @var TwigEnvironment
	 */
	public $twig;
	/**
	 * @var string
	 */
	public $uri;
	/**
	 * @var User
	 */
	public $user;
	/**
	 * @var mixed
	 */
	public $view;

	/**
	 * @return void
	 */
	static public function main () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:454: characters 4-39
		error_reporting(E_ALL);
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:455: characters 4-41
		ini_set("display_errors", "1");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:462: characters 3-68
		require_once((dirname($_SERVER["SCRIPT_FILENAME"])??'null') . "/" . "/../vendor/autoload.php");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:473: characters 3-26
		\App::$current = new \App();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:474: characters 3-33
		$a = \App::$current;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:476: characters 3-18
		$a->sendHeaders();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:478: lines 478-481
		if (!$a->init()) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:479: characters 4-12
			$a = null;
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:480: characters 4-10
			return;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:482: characters 3-10
		$a->run();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:483: characters 3-11
		$a = null;
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:32: lines 32-34
		if (BaseApp::$config === null) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:33: characters 4-16
			$this->loadConfig();
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:36: characters 3-21
		$this->cookieName = "sid";
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:37: characters 3-39
		$this->cookieDomain = "." . (\App::$config->HOST??'null');
	}

	/**
	 * Override this function if you want
	 * to insert some actions
	 * 
	 * @return void
	 */
	public function beforeDispatch () {
	}

	/**
	 * @return void
	 */
	public function cloneApp () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:423: characters 3-23
		$app = new \App();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:424: characters 3-28
		$bapp = $app;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:425: characters 3-17
		$bapp->cnx = $this->cnx;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:426: characters 3-30
		$bapp->view = BaseView::init();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:427: characters 3-20
		\App::$current = $app;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:428: characters 3-18
		$bapp->mainLoop();
	}

	/**
	 * Detect lang from HTTP headers
	 * 
	 * @return string
	 */
	public function detectLang () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:168: characters 3-50
		$l = PhpWeb::getClientHeader("Accept-Language");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:169: lines 169-177
		if ($l !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:170: lines 170-177
			$_g = 0;
			$_g1 = HxString::split($l, ",");
			while ($_g < $_g1->length) {
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:170: characters 9-10
				$l1 = ($_g1->arr[$_g] ?? null);
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:170: lines 170-177
				++$_g;
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:171: characters 5-24
				$l1 = (HxString::split($l1, ";")->arr[0] ?? null);
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:172: characters 5-24
				$l1 = (HxString::split($l1, "-")->arr[0] ?? null);
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:173: characters 5-28
				$l1 = trim($l1);
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:174: lines 174-176
				$_g2 = 0;
				$_g11 = \App::$config->LANGS;
				while ($_g2 < $_g11->length) {
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:174: characters 10-11
					$a = ($_g11->arr[$_g2] ?? null);
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:174: lines 174-176
					++$_g2;
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:175: lines 175-176
					if ($a === $l1) {
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:176: characters 7-15
						return $a;
					}
				}

			}
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:179: characters 3-25
		return \App::$config->LANG;
	}

	/**
	 * @param mixed $e
	 * 
	 * @return void
	 */
	public function errorHandler ($e) {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:341: lines 341-380
		try {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:342: characters 4-73
			$stack = CallStack::toString(CallStack::exceptionStack());
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:344: lines 344-347
			if ($this->cnx !== null) {
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:345: characters 5-19
				$this->cnx->rollback();
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:346: characters 5-22
				$this->logError($e, $stack);
			}
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:354: characters 4-19
			$this->maintain = true;
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:355: characters 4-26
			$this->view = BaseView::init();
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:357: characters 4-22
			$this->view->exception = $e;
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:358: characters 4-32
			$this->view->message = \Std::string($e);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:360: lines 360-362
			if (\App::$config->DEBUG || (($this->user !== null) && $this->user->isAdmin())) {
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:361: characters 5-23
				$this->view->stack = $stack;
			}
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:364: characters 4-29
			$this->setTemplate("error.twig");
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:365: characters 4-26
			$this->executeTemplate(false);
		} catch (\Throwable $__hx__caught_e) {
			CallStack::saveExceptionTrace($__hx__caught_e);
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e1 = $__hx__real_e;
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:368: characters 4-22
			echo("<pre>");
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:369: characters 27-71
			$v = null;
			try {
				$v = \Std::string($e1);
			} catch (\Throwable $__hx__caught_e) {
				CallStack::saveExceptionTrace($__hx__caught_e);
				$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
				$e2 = $__hx__real_e;
				$v = "???";
			}
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:369: characters 4-72
			echo((\Std::string("Error : " . ($v??'null'))??'null') . "\x0A");

			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:370: characters 4-73
			echo((\Std::string(CallStack::toString(CallStack::exceptionStack()))??'null') . "\x0A");
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:371: lines 371-378
			try {
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:372: lines 372-373
				if ($this->cnx !== null) {
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:373: characters 6-41
					Error::$manager->unsafeGet(0, false);
				}
			} catch (\Throwable $__hx__caught_e) {
				CallStack::saveExceptionTrace($__hx__caught_e);
				$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
				$e3 = $__hx__real_e;
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:375: characters 5-44
				echo("Initializing Database..." . "\x0A");
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:376: characters 5-44
				Admin::initializeDatabase();
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:377: characters 5-24
				echo("Done" . "\x0A");
			}
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:379: characters 4-23
			echo("</pre>");
		}
	}

	/**
	 * Render the current page with template engine
	 * 
	 * @param bool $save
	 * 
	 * @return void
	 */
	public function executeTemplate ($save = null) {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:128: characters 3-65
		$loader = new \Twig_Loader_Filesystem("../lang/master/tpl");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:129: lines 129-131
		$this->twig = new TwigEnvironment($loader, new HxAnon(["debug" => \App::$config->DEBUG]));
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:134: lines 134-136
		if (\App::$config->DEBUG) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:135: characters 4-49
			$this->twig->addExtension(new \Twig_Extension_Debug());
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:139: characters 3-25
		$app = \App::$current;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:140: characters 3-23
		$this->view->user = $app->user;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:141: characters 3-29
		$this->view->session = $app->session;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:142: characters 18-56
		$tmp = ($app->user !== null) && $app->user->isAdmin();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:142: characters 3-56
		$this->view->isAdmin = $tmp;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:144: characters 3-44
		$result = $this->twig->render($this->template, $this->view);
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:145: characters 3-29
		if ($save) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:145: characters 15-29
			$this->saveAndClose();
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:147: characters 3-20
		echo(\Std::string($result));
	}

	/**
	 * Get current application langage (2 letters lowercase)
	 * 
	 * @return string
	 */
	public function getLang () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:211: characters 10-106
		if (($this->session !== null) && ($this->session->lang !== null) && ($this->session->lang !== "")) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:211: characters 76-88
			return $this->session->lang;
		} else {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:211: characters 91-106
			return \App::$config->LANG;
		}
	}

	/**
	 * init template engine
	 * and db connexion
	 * 
	 * @return bool
	 */
	public function init () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:388: characters 3-44
		$this->maintain = \App::$config->getBool("maintain");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:389: lines 389-394
		if ($this->maintain) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:390: characters 4-26
			$this->view = BaseView::init();
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:391: characters 4-32
			$this->setTemplate("maintain.twig");
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:392: characters 4-26
			$this->executeTemplate(false);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:393: characters 4-16
			return false;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:395: lines 395-413
		try {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:396: characters 4-43
			$dbstr = \App::$config->get("database");
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:397: characters 4-74
			$dbreg = new \EReg("([^:]+)://([^:]+):([^@]*?)@([^:]+)(:[0-9]+)?/(.*?)\$", "");
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:398: lines 398-399
			if (!$dbreg->match($dbstr)) {
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:399: characters 5-10
				throw new HxException("Configuration requires a valid database attribute, format is : mysql://user:password@host:port/dbname");
			}
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:400: characters 4-32
			$port = $dbreg->matched(5);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:402: characters 10-26
			$dbparams = $dbreg->matched(2);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:403: characters 10-26
			$dbparams1 = $dbreg->matched(3);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:404: characters 10-26
			$dbparams2 = $dbreg->matched(4);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:405: characters 10-60
			$dbparams3 = ($port === null ? 3306 : \Std::parseInt(mb_substr($port, 1, null)));
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:401: lines 401-408
			$dbparams4 = new HxAnon([
				"user" => $dbparams,
				"pass" => $dbparams1,
				"host" => $dbparams2,
				"port" => $dbparams3,
				"database" => $dbreg->matched(6),
				"socket" => null,
			]);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:409: characters 4-40
			$this->cnx = Mysql::connect($dbparams4);
		} catch (\Throwable $__hx__caught_e) {
			CallStack::saveExceptionTrace($__hx__caught_e);
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:411: characters 4-19
			$this->errorHandler($e);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:412: characters 4-16
			return false;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:418: characters 3-14
		return true;
	}

	/**
	 * @param string $lang
	 * 
	 * @return bool
	 */
	public function initLang ($lang) {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:84: characters 3-53
		if (($lang === null) || ($lang === "")) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:84: characters 35-53
			$lang = BaseApp::$config->LANG;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:87: characters 3-12
		$path = null;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:88: lines 88-92
		if (!\App::$config->DEBUG) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:89: characters 4-49
			$path = (dirname($_SERVER["SCRIPT_FILENAME"])??'null') . "/" . "../lang/" . ($lang??'null') . "/";
		} else {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:91: characters 4-43
			$path = (dirname($_SERVER["SCRIPT_FILENAME"])??'null') . "/" . "../lang/master/";
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:94: characters 3-33
		\App::$config->TPL = ($path??'null') . "tpl/";
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:95: characters 3-37
		\App::$config->TPL_TMP = ($path??'null') . "tmp/";
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:98: lines 98-100
		if (setlocale(LC_TIME, "en_US.UTF-8") === false) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:99: characters 4-27
			setlocale(LC_TIME, "en");
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:103: characters 3-31
		Locale::init($lang);
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:105: characters 3-14
		return true;
	}

	/**
	 * @return void
	 */
	public function loadConfig () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:50: characters 3-51
		\App::$config = BaseApp::$config = new Config();
	}

	/**
	 * @param string $templatePath
	 * 
	 * @return void
	 */
	public function loadTemplate ($templatePath) {
	}

	/**
	 * @param mixed $e
	 * @param string $stack
	 * 
	 * @return void
	 */
	public function logError ($e, $stack = null) {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:324: characters 3-103
		$stack1 = ($stack !== null ? $stack : CallStack::toString(CallStack::exceptionStack()));
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:325: characters 3-33
		$message = new \StringBuf();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:326: characters 3-29
		$message->add(\Std::string($e));
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:327: characters 3-20
		$message->add("\x0A");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:328: characters 3-21
		$message->add($stack1);
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:329: characters 3-20
		$message->add("\x0A");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:330: characters 3-32
		$e1 = new Error();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:331: characters 3-23
		$e1->url = PhpWeb::getURI();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:332: characters 3-27
		$e1->ip = $_SERVER["REMOTE_ADDR"];
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:333: characters 3-45
		$e1->set_user(($this->user !== null ? $this->user : null));
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:334: characters 3-22
		$e1->date = \Date::now();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:335: characters 3-50
		$e1->userAgent = PhpWeb::getClientHeader("User-Agent");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:336: characters 3-31
		$e1->error = $message->b;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:337: characters 3-13
		$e1->insert();
	}

	/**
	 * @return void
	 */
	public function mainLoop () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:229: characters 3-27
		$this->params = PhpWeb::getParams();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:232: characters 3-17
		$sids = new \Array_hx();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:233: characters 3-52
		$cookieSid = (PhpWeb::getCookies()->data[$this->cookieName] ?? null);
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:234: characters 3-58
		if (array_key_exists("sid", $this->params->data)) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:234: characters 30-58
			$x = ($this->params->data["sid"] ?? null);
			$sids->arr[$sids->length] = $x;
			++$sids->length;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:235: characters 3-47
		if ($cookieSid !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:235: characters 27-47
			$sids->arr[$sids->length] = $cookieSid;
			++$sids->length;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:236: characters 3-40
		$this->session = Session::init($sids);
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:239: characters 3-55
		$this->maintain = Variable::getInt("maintain") !== 0;
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:240: characters 3-22
		$this->user = $this->session->get_user();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:243: characters 3-14
		$this->setupLang();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:246: lines 246-247
		if ($this->maintain && (($this->user !== null) && $this->user->isAdmin())) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:247: characters 4-20
			$this->maintain = false;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:249: characters 3-23
		$this->setCookie($cookieSid);
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:251: lines 251-255
		if ($this->maintain) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:252: characters 4-32
			$this->setTemplate("maintain.twig");
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:253: characters 4-21
			$this->executeTemplate();
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:254: characters 4-10
			return;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:258: lines 258-305
		try {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:260: characters 4-22
			$this->uri = PhpWeb::getURI();
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:261: characters 4-72
			if (\StringTools::endsWith($this->uri, "/index.n")) {
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:261: characters 49-72
				$this->uri = mb_substr($this->uri, 0, -8);
			}
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:264: characters 4-20
			$this->beforeDispatch();
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:266: characters 4-47
			$d = new Dispatch($this->uri, $this->params);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:267: characters 4-21
			$d->onMeta = Boot::getInstanceClosure($this, 'onMeta');
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:268: characters 4-37
			$d->runtimeDispatch(Dispatch::extractConfig(new Main()));
		} catch (\Throwable $__hx__caught_e) {
			CallStack::saveExceptionTrace($__hx__caught_e);
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			if ($__hx__real_e instanceof DispatchError) {
				$e = $__hx__real_e;
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:273: lines 273-279
				if (\App::$config->DEBUG) {
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:277: characters 5-23
					throw (is_object($__hx__throw = $e) && $__hx__throw instanceof \Throwable ? $__hx__throw : new HxException($__hx__throw));
				}
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:280: characters 4-18
				$this->cnx->rollback();
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:281: characters 4-21
				PhpWeb::redirect("/");
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:282: characters 4-10
				return;
			} else if ($__hx__real_e instanceof ControllerAction) {
				$e1 = $__hx__real_e;
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:286: lines 286-304
				$__hx__switch = ($e1->index);
				if ($__hx__switch === 0) {
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:287: characters 24-27
					$url = $e1->params[0];
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:288: characters 5-22
					PhpWeb::redirect($url);
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:289: characters 5-20
					$this->template = null;

				} else if ($__hx__switch === 1) {
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:290: characters 26-30
					$text = $e1->params[1];
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:290: characters 21-24
					$url1 = $e1->params[0];
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:291: lines 291-294
					if ($text === null) {
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:292: characters 6-16
						$text = $url1;
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:293: characters 6-24
						$url1 = PhpWeb::getURI();
					}
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:295: characters 5-22
					PhpWeb::redirect($url1);
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:296: characters 5-74
					$error = $e1->index === 1;
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:297: characters 5-27
					if ($error) {
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:297: characters 17-27
						$this->rollback();
					}
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:298: lines 298-302
					if ($error) {
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:299: characters 6-35
						$this->session->addMessage($text, true);
					} else {
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:301: characters 6-30
						$this->session->addMessage($text);
					}
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:303: characters 5-20
					$this->template = null;

				} else if ($__hx__switch === 2) {
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:290: characters 46-50
					$text1 = $e1->params[1];
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:290: characters 42-45
					$url2 = $e1->params[0];
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:291: lines 291-294
					if ($text1 === null) {
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:292: characters 6-16
						$text1 = $url2;
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:293: characters 6-24
						$url2 = PhpWeb::getURI();
					}
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:295: characters 5-22
					PhpWeb::redirect($url2);
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:296: characters 5-74
					$error1 = $e1->index === 1;
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:297: characters 5-27
					if ($error1) {
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:297: characters 17-27
						$this->rollback();
					}
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:298: lines 298-302
					if ($error1) {
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:299: characters 6-35
						$this->session->addMessage($text1, true);
					} else {
						#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:301: characters 6-30
						$this->session->addMessage($text1);
					}
					#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:303: characters 5-20
					$this->template = null;

				}
			} else  throw $__hx__caught_e;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:308: lines 308-312
		if ($this->template === null) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:309: characters 4-18
			$this->saveAndClose();
		} else {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:311: characters 4-25
			$this->executeTemplate(true);
		}
	}

	/**
	 * @param string $m
	 * @param \Array_hx $args
	 * 
	 * @return void
	 */
	public function onMeta ($m, $args) {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:151: lines 151-161
		if ($m === "admin") {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:158: lines 158-159
			if (($this->user === null) || !$this->user->isAdmin()) {
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:159: characters 5-10
				throw new HxException(ControllerAction::RedirectAction("/"));
			}
		} else if ($m === "logged") {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:155: lines 155-156
			if ($this->user === null) {
				#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:156: characters 5-10
				throw new HxException(ControllerAction::RedirectAction("/?__redirect=" . (PhpWeb::getURI()??'null')));
			}
		} else if ($m === "tpl") {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:153: characters 4-24
			$this->setTemplate(($args->arr[0] ?? null));
		} else {
		}
	}

	/**
	 * @return void
	 */
	public function rollback () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:215: characters 3-35
		if ($this->cnx !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:215: characters 21-35
			$this->cnx->rollback();
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:216: characters 3-27
		Manager::cleanup();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:217: lines 217-218
		if (($this->user !== null) && ($this->session !== null)) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:218: characters 4-23
			$this->user = $this->session->get_user();
		}
	}

	/**
	 * @return void
	 */
	public function run () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:434: characters 3-108
		Transaction::main($this->cnx, Boot::getInstanceClosure($this, 'cloneApp'), function ($e) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:434: characters 56-86
			$b = \App::$current;
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:434: characters 87-104
			$b->errorHandler($e);
		});
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:435: characters 3-21
		\App::$current = null;
	}

	/**
	 * Update session and close connection to database
	 * 
	 * @return void
	 */
	public function saveAndClose () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:113: characters 3-27
		if ($this->cnx === null) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:113: characters 21-27
			return;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:114: lines 114-115
		if ($this->session->sid !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:115: characters 4-20
			$this->session->update();
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:117: characters 3-15
		$this->cnx->commit();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:118: characters 3-14
		$this->cnx->close();
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:119: characters 11-36
		$this->cnx->close = function () {
		};
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:120: characters 11-48
		$this->cnx->request = function ($s) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:120: characters 37-48
			return null;
		};
	}

	/**
	 * @return void
	 */
	public function sendHeaders () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:439: characters 3-72
		header("Cache-Control" . ": " . "no-store, no-cache, must-revalidate");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:440: characters 3-38
		header("Pragma" . ": " . "no-cache");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:441: characters 3-33
		header("Expires" . ": " . "-1");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:442: characters 3-66
		header("P3P" . ": " . "CP=\"ALL DSP COR NID CURa OUR STP PUR\"");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:443: characters 3-60
		header("Content-Type" . ": " . "text/html; Charset=UTF-8");
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:444: characters 3-60
		header("Expires" . ": " . "Mon, 26 Jul 1997 05:00:00 GMT");
	}

	/**
	 * @param string $oldCookie
	 * 
	 * @return void
	 */
	public function setCookie ($oldCookie) {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:223: lines 223-225
		if (($this->session !== null) && ($this->session->sid !== null) && ($this->session->sid !== $oldCookie)) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:224: characters 4-75
			header("Set-Cookie" . ": " . ((($this->cookieName??'null') . "=" . ($this->session->sid??'null') . "; path=/;")??'null'));
		}
	}

	/**
	 * Define wich template will render the page
	 * 
	 * @param string $t
	 * 
	 * @return void
	 */
	public function setTemplate ($t) {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:79: characters 3-15
		$this->template = $t;
	}

	/**
	 * Setup current app language
	 * 
	 * @return void
	 */
	public function setupLang () {
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:189: characters 3-42
		if (\App::$config->LANG === "master") {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:189: characters 36-42
			return;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:192: lines 192-194
		if (($this->session->lang === null) || !\Lambda::has(\App::$config->LANGS, $this->session->lang)) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:193: characters 19-60
			$tmp = ($this->user === null ? $this->detectLang() : $this->user->lang);
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:193: characters 4-60
			$this->session->lang = $tmp;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:197: characters 3-33
		$lang = ($this->params->data["lang"] ?? null);
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:198: lines 198-201
		if (($lang !== null) && \Lambda::has(\App::$config->LANGS, $lang)) {
			#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:199: characters 4-23
			$this->session->lang = $lang;
		}
		#/home/bubar/projects/sugoi/src/sugoi/BaseApp.hx:204: characters 3-25
		$this->initLang($this->session->lang);
	}
}

Boot::registerClass(BaseApp::class, 'sugoi.BaseApp');
