<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\mail;

use \php\Boot;

/**
 * Interface for "Mailers"
 *
 * @author fbarbut
 */
interface IMailer {
	/**
	 * init with a configuration object
	 * 
	 * @param object $conf
	 * 
	 * @return IMailer
	 */
	public function init ($conf = null) ;

	/**
	 * Sends an email. A callback can be defined to handle the result
	 * 
	 * @param IMail $email
	 * @param mixed $params
	 * @param \Closure $callback
	 * 
	 * @return void
	 */
	public function send ($email, $params = null, $callback = null) ;
}

Boot::registerClass(IMailer::class, 'sugoi.mail.IMailer');
