<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace haxe\io;

use \haxe\io\_BytesData\Container;
use \php\Boot;

class StringInput extends BytesInput {
	/**
	 * @param string $s
	 * 
	 * @return void
	 */
	public function __construct ($s) {
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/haxe/io/StringInput.hx:31: characters 10-35
		$tmp = strlen($s);
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/haxe/io/StringInput.hx:31: characters 3-37
		parent::__construct(new Bytes($tmp, new Container($s)));
	}
}

Boot::registerClass(StringInput::class, 'haxe.io.StringInput');
