<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sourcemap\_Mapping;

use \php\_Boot\HxAnon;
use \php\Boot;

final class Mapping_Impl_ {
	/**
	 * @var int
	 */
	const COLUMN = 3;
	/**
	 * @var int
	 */
	const GENERATED_COLUMN = 0;
	/**
	 * @var int
	 */
	const LINE = 2;
	/**
	 * @var int
	 */
	const NAME = 4;
	/**
	 * @var int
	 */
	const SOURCE = 1;


	/**
	 * @param \Array_hx $data
	 * 
	 * @return \Array_hx
	 */
	static public function _new ($data) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:24: character 2
		$this1 = $data;
		return $this1;
	}

	/**
	 * @param \Array_hx $this
	 * @param \SourceMap $map
	 * @param int $generatedLine
	 * 
	 * @return object
	 */
	static public function getSourcePos ($this1, $map, $generatedLine) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:29: lines 29-32
		$pos = new HxAnon([
			"generatedLine" => $generatedLine,
			"generatedColumn" => ($this1->arr[0] ?? null),
		]);
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:33: lines 33-40
		if ($this1->length > 1) {
			#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:34: characters 4-31
			$pos->originalLine = ($this1->arr[2] ?? null) + 1;
			#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:35: characters 4-31
			$pos->originalColumn = ($this1->arr[3] ?? null);
			#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:36: characters 4-53
			$pos->source = ($map->sourceRoot??'null') . (($map->sources->arr[($this1->arr[1] ?? null)] ?? null)??'null');
			#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:37: lines 37-39
			if ($this1->length > 4) {
				#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:38: characters 5-31
				$pos->name = ($map->names->arr[($this1->arr[4] ?? null)] ?? null);
			}
		}
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:41: characters 3-13
		return $pos;
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return int
	 */
	static public function get_column ($this1) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:58: characters 32-51
		return ($this1->arr[3] ?? null);
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return int
	 */
	static public function get_generatedColumn ($this1) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:55: characters 41-70
		return ($this1->arr[0] ?? null);
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return int
	 */
	static public function get_line ($this1) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:57: characters 30-47
		return ($this1->arr[2] ?? null);
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return int
	 */
	static public function get_name ($this1) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:59: characters 30-47
		return ($this1->arr[4] ?? null);
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return int
	 */
	static public function get_source ($this1) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:56: characters 32-51
		return ($this1->arr[1] ?? null);
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return bool
	 */
	static public function hasColumn ($this1) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:46: characters 45-72
		return $this1->length > 3;
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return bool
	 */
	static public function hasLine ($this1) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:45: characters 43-68
		return $this1->length > 2;
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return bool
	 */
	static public function hasName ($this1) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:47: characters 43-68
		return $this1->length > 4;
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return bool
	 */
	static public function hasSource ($this1) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:44: characters 45-72
		return $this1->length > 1;
	}

	/**
	 * @param \Array_hx $this
	 * @param int $offset
	 * 
	 * @return void
	 */
	static public function offsetColumn ($this1, $offset) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:52: characters 51-73
		$this1[3] += $offset;
	}

	/**
	 * @param \Array_hx $this
	 * @param int $offset
	 * 
	 * @return void
	 */
	static public function offsetGeneratedColumn ($this1, $offset) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:49: characters 60-92
		$this1[0] += $offset;
	}

	/**
	 * @param \Array_hx $this
	 * @param int $offset
	 * 
	 * @return void
	 */
	static public function offsetLine ($this1, $offset) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:51: characters 49-69
		$this1[2] += $offset;
	}

	/**
	 * @param \Array_hx $this
	 * @param int $offset
	 * 
	 * @return void
	 */
	static public function offsetName ($this1, $offset) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:53: characters 49-69
		$this1[4] += $offset;
	}

	/**
	 * @param \Array_hx $this
	 * @param int $offset
	 * 
	 * @return void
	 */
	static public function offsetSource ($this1, $offset) {
		#/home/bubar/haxe/haxe_libraries/sourcemap/1.0.0/haxelib/src/sourcemap/Mapping.hx:50: characters 51-73
		$this1[1] += $offset;
	}
}

Boot::registerClass(Mapping_Impl_::class, 'sourcemap._Mapping.Mapping_Impl_');
Boot::registerGetters('sourcemap\\_Mapping\\Mapping_Impl_', [
	'name' => true,
	'column' => true,
	'line' => true,
	'source' => true,
	'generatedColumn' => true
]);
