<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\form;

use \php\Boot;
use \php\_Boot\HxString;
use \haxe\ds\List_hx;
use \php\_Boot\HxException;
use \sugoi\form\validators\Validator;
use \sugoi\form\filters\IFilter;

class FormElement {
	/**
	 * @var bool
	 */
	public $active;
	/**
	 * @var string
	 */
	public $attributes;
	/**
	 * @var string
	 */
	public $cssClass;
	/**
	 * @var string
	 */
	public $description;
	/**
	 * @var List_hx
	 */
	public $errors;
	/**
	 * @var List_hx
	 */
	public $filters;
	/**
	 * @var bool
	 */
	public $inited;
	/**
	 * @var bool
	 */
	public $internal;
	/**
	 * @var string
	 */
	public $label;
	/**
	 * @var string
	 */
	public $name;
	/**
	 * @var Form
	 */
	public $parentForm;
	/**
	 * @var bool
	 */
	public $required;
	/**
	 * @var List_hx
	 */
	public $validators;
	/**
	 * @var mixed
	 */
	public $value;

	/**
	 * @return void
	 */
	public function __construct () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:31: characters 3-16
		$this->active = true;
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:32: characters 3-22
		$this->errors = new List_hx();
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:33: characters 3-26
		$this->validators = new List_hx();
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:34: characters 3-23
		$this->filters = new List_hx();
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:35: characters 3-17
		$this->inited = false;
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:36: characters 3-19
		$this->internal = false;
	}

	/**
	 * @param IFilter $filter
	 * 
	 * @return void
	 */
	public function addFilter ($filter) {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:88: characters 3-22
		$this->filters->add($filter);
	}

	/**
	 * @param Validator $validator
	 * 
	 * @return void
	 */
	public function addValidator ($validator) {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:84: characters 3-28
		$this->validators->add($validator);
	}

	/**
	 * apply all linked filter to the data
	 * 
	 * @return mixed
	 */
	public function filter () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:43: characters 14-21
		$_g_head = $this->filters->h;
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:43: lines 43-45
		while ($_g_head !== null) {
			$val = $_g_head->item;
			$_g_head = $_g_head->next;
			$f = $val;
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:44: characters 4-9
			$this->value = $f->filter($this->value);
		}

		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:46: characters 3-15
		return $this->value;
	}

	/**
	 * Return CSS classes of the element
	 * 
	 * @return string
	 */
	public function getClasses () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:196: characters 3-71
		$css = ($this->cssClass !== null ? $this->cssClass : $this->parentForm->defaultClass);
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:198: lines 198-204
		if ($this->required && $this->parentForm->isSubmitted()) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:200: lines 200-201
			if ($this->value === null) {
				#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:201: characters 5-47
				$css = ($css??'null') . " " . ($this->parentForm->requiredErrorClass??'null');
			}
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:202: lines 202-203
			if (!$this->isValid()) {
				#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:203: characters 5-46
				$css = ($css??'null') . " " . ($this->parentForm->invalidErrorClass??'null');
			}
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:205: characters 3-27
		if ($css === null) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:205: characters 19-27
			$css = "";
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:206: characters 3-20
		return trim($css);
	}

	/**
	 * @return string
	 */
	public function getErrorClasses () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:211: characters 3-16
		$css = "";
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:213: lines 213-219
		if ($this->required && $this->parentForm->isSubmitted()) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:215: lines 215-216
			if ($this->value === null) {
				#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:216: characters 5-47
				$css = ($css??'null') . " " . ($this->parentForm->requiredErrorClass??'null');
			}
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:217: lines 217-218
			if (!$this->isValid()) {
				#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:218: characters 5-46
				$css = ($css??'null') . " " . ($this->parentForm->invalidErrorClass??'null');
			}
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:221: characters 3-20
		return trim($css);
	}

	/**
	 * @return List_hx
	 */
	public function getErrors () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:116: characters 3-12
		$this->isValid();
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:118: characters 15-25
		$_g_head = $this->validators->h;
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:118: lines 118-120
		while ($_g_head !== null) {
			$val = $_g_head->item;
			$_g_head = $_g_head->next;
			$val1 = $val;
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:119: characters 15-25
			$_g_head1 = $val1->errors->h;
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:119: lines 119-120
			while ($_g_head1 !== null) {
				$val2 = $_g_head1->item;
				$_g_head1 = $_g_head1->next;
				$err = $val2;
				#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:120: characters 5-80
				$this->errors->add("<span class=\"formErrorsField\">" . ($this->label??'null') . "</span> : " . ($err??'null'));
			}

		}

		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:122: characters 3-16
		return $this->errors;
	}

	/**
	 * renders the element with label+tr+td...
	 * 
	 * @return string
	 */
	public function getFullRow () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:146: characters 3-27
		$s = new \StringBuf();
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:147: characters 3-69
		if (Form::$USE_TWITTER_BOOTSTRAP) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:147: characters 34-69
			$s->add("<div class=\"form-group\">\x0A");
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:148: characters 3-20
		$s->add($this->getLabel());
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:149: characters 3-61
		$s->add("<div class='col-sm-8'>" . ($this->render()??'null') . "</div>");
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:150: characters 3-52
		if (Form::$USE_TWITTER_BOOTSTRAP) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:150: characters 35-52
			$s->add("</div>\x0A");
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:151: characters 3-22
		return $s->b;
	}

	/**
	 * @return string
	 */
	public function getLabel () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:187: characters 3-40
		$n = ($this->parentForm->name??'null') . "_" . ($this->name??'null');
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:188: characters 3-162
		return "<label for=\"" . ($n??'null') . "\" class=\"" . ($this->getLabelClasses()??'null') . "\" id=\"" . ($n??'null') . "__Label\">" . ($this->label??'null') . ((($this->required ? $this->parentForm->labelRequiredIndicator : ""))??'null') . "</label>";
	}

	/**
	 * Get CSS classes for the form element label
	 * 
	 * @return string
	 */
	public function getLabelClasses () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:164: characters 3-16
		$css = "";
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:165: characters 3-65
		if (Form::$USE_TWITTER_BOOTSTRAP) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:165: characters 35-65
			$css = "col-sm-4 control-label";
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:167: characters 3-27
		$requiredSet = false;
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:168: lines 168-174
		if ($this->required) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:169: characters 4-39
			$css = ($css??'null') . " " . ($this->parentForm->requiredClass??'null');
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:170: lines 170-173
			if ($this->parentForm->isSubmitted() && $this->required && ($this->value === null)) {
				#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:171: characters 5-45
				$css = ($css??'null') . " " . ($this->parentForm->requiredErrorClass??'null');
				#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:172: characters 5-23
				$requiredSet = true;
			}
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:175: lines 175-177
		if (!$requiredSet && $this->parentForm->isSubmitted() && !$this->isValid()) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:176: characters 4-43
			$css = ($css??'null') . " " . ($this->parentForm->invalidErrorClass??'null');
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:182: characters 3-13
		return $css;
	}

	/**
	 * @return string
	 */
	public function getType () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:156: characters 3-41
		return \Std::string(\Type::getClass($this));
	}

	/**
	 * From string (web param) to typed value.
	 * This method is in charge of cleaning the input which may be unsafe ( triming, escaping ...)
	 * 
	 * @param string $str
	 * 
	 * @return mixed
	 */
	public function getTypedValue ($str) {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:111: characters 3-8
		throw new HxException("getTypedValue() function not implemented in \"" . ($this->name??'null') . "\"");
	}

	/**
	 * get element value with the correct type
	 * 
	 * @return mixed
	 */
	public function getValue () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:240: characters 3-15
		return $this->value;
	}

	/**
	 * @return void
	 */
	public function init () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:80: characters 3-16
		$this->inited = true;
	}

	/**
	 * Checks if the current value of the elements is valid
	 * 
	 * @return bool
	 */
	public function isValid () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:54: characters 3-17
		$this->errors->clear();
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:56: characters 3-27
		if (!$this->active) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:56: characters 16-27
			return true;
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:58: lines 58-62
		if (($this->value === null) && $this->required) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:60: characters 4-139
			$this->errors->add("<span class=\"formErrorsField\">\"" . (((($this->label !== null) && ($this->label !== "") ? $this->label : $this->name))??'null') . "\"</span> ne doit pas être vide.");
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:61: characters 4-16
			return false;
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:64: lines 64-75
		if ($this->value !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:66: lines 66-72
			if (!$this->validators->isEmpty()) {
				#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:67: characters 23-33
				$_g_head = $this->validators->h;
				#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:67: lines 67-70
				while ($_g_head !== null) {
					$val = $_g_head->item;
					$_g_head = $_g_head->next;
					$validator = $val;
					#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:69: characters 6-50
					if (!$validator->isValid($this->value)) {
						#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:69: characters 38-50
						return false;
					}
				}
			}
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:74: characters 4-15
			return true;
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:76: characters 3-14
		return true;
	}

	/**
	 * Fill the element with a value taken from the web params
	 * 
	 * @return void
	 */
	public function populate () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:96: characters 3-22
		if (!$this->inited) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:96: characters 16-22
			$this->init();
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:98: characters 3-40
		$n = ($this->parentForm->name??'null') . "_" . ($this->name??'null');
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:99: characters 3-37
		$v = (\App::$current->params->data[$n] ?? null);
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:100: characters 3-27
		$this->value = $this->getTypedValue($v);
	}

	/**
	 * @return bool
	 */
	public function remove () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:136: lines 136-138
		if ($this->parentForm !== null) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:137: characters 4-41
			return $this->parentForm->removeElement($this);
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:139: characters 3-15
		return false;
	}

	/**
	 * Render the element in HTML
	 * 
	 * @return string
	 */
	public function render () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:130: characters 3-22
		if (!$this->inited) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:130: characters 16-22
			$this->init();
		}
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:131: characters 3-27
		return \Std::string($this->value);
	}

	/**
	 * @param mixed $s
	 * 
	 * @return string
	 */
	public function safeString ($s) {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:225: characters 10-79
		if ($s === null) {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:225: characters 22-24
			return "";
		} else {
			#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:225: characters 27-79
			return HxString::split(htmlspecialchars(\Std::string($s), (null ? ENT_QUOTES | ENT_HTML401 : ENT_NOQUOTES)), "\"")->join("&quot;");
		}
	}

	/**
	 * Renders the element in HTML
	 * 
	 * @return string
	 */
	public function toString () {
		#/home/bubar/projects/sugoi/src/sugoi/form/FormElement.hx:233: characters 3-18
		return $this->render();
	}

	public function __toString() {
		return $this->toString();
	}
}

Boot::registerClass(FormElement::class, 'sugoi.form.FormElement');
