<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\form;

use \php\Boot;

interface Formatter {
	/**
	 * @param mixed $data
	 * 
	 * @return string
	 */
	public function format ($data) ;
}

Boot::registerClass(Formatter::class, 'sugoi.form.Formatter');
