<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sugoi\db;

use \php\_Boot\HxAnon;
use \php\Boot;
use \haxe\CallStack;
use \sys\db\Object_hx;
use \sys\db\Manager;
use \haxe\Unserializer;
use \php\_Boot\HxException;
use \db\User;
use \haxe\Serializer;

class Session extends Object_hx {
	/**
	 * @var string
	 * Generate a random 32 chars string
	 */
	static public $S = "abcdefjhijklmnopqrstuvwxyABCDEFJHIJKLMNOPQRSTUVWXYZ0123456789";
	/**
	 * @var Manager
	 */
	static public $manager;

	/**
	 * @var object
	 */
	public $cache_messages;
	/**
	 * @var \Date
	 */
	public $createTime;
	/**
	 * @var mixed
	 */
	public $data;
	/**
	 * @var mixed
	 */
	public $data_messages;
	/**
	 * @var string
	 */
	public $ip;
	/**
	 * @var string
	 */
	public $lang;
	/**
	 * @var \Date
	 */
	public $lastTime;
	/**
	 * @var \Array_hx
	 */
	public $messages;
	/**
	 * @var string
	 */
	public $sdata;
	/**
	 * @var string
	 */
	public $sid;
	/**
	 * @var mixed
	 */
	public $uid;
	/**
	 * @var User
	 */
	public $user;

	/**
	 * Delete old sessions
	 * 
	 * @return void
	 */
	static public function clean () {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:124: characters 3-80
		Session::$manager->unsafeDelete("DELETE FROM Session WHERE lastTime<" . (Manager::quoteAny(\Date::fromTime(\Date::now()->getTime() + -7776000000.))??'null'));
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:126: characters 3-93
		Session::$manager->unsafeDelete("DELETE FROM Session WHERE lastTime<" . (Manager::quoteAny(\Date::fromTime(\Date::now()->getTime() + -2592000000.))??'null') . " AND uid IS NULL");
	}

	/**
	 * @return string
	 */
	static public function generateId () {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:112: characters 3-15
		$id = "";
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:113: lines 113-115
		$_g = 0;
		while ($_g < 32) {
			$x = $_g++;
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:114: characters 19-39
			$x1 = mb_strlen(Session::$S);
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:114: characters 4-42
			$id = ($id??'null') . (mb_substr(Session::$S, ($x1 <= 1 ? 0 : mt_rand(0, $x1 - 1)), 1)??'null');
		}

		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:116: characters 3-12
		return $id;
	}

	/**
	 * @param string $sid
	 * 
	 * @return Session
	 */
	static public function get ($sid) {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:63: characters 3-33
		if ($sid === null) {
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:63: characters 22-33
			return null;
		}
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:65: characters 3-33
		$s = Session::$manager->unsafeGet($sid, true);
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:66: characters 3-31
		if ($s === null) {
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:66: characters 20-31
			return null;
		}
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:67: lines 67-75
		try {
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:71: characters 4-43
			$s->data = Unserializer::run($s->sdata);
		} catch (\Throwable $__hx__caught_e) {
			CallStack::saveExceptionTrace($__hx__caught_e);
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:74: characters 4-17
			$s->data = null;
		}
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:77: characters 3-11
		return $s;
	}

	/**
	 * @param \Array_hx $sids
	 * 
	 * @return Session
	 */
	static public function init ($sids) {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:82: lines 82-85
		$_g = 0;
		while ($_g < $sids->length) {
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:82: characters 8-11
			$sid = ($sids->arr[$_g] ?? null);
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:82: lines 82-85
			++$_g;
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:83: characters 4-21
			$s = Session::get($sid);
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:84: characters 4-28
			if ($s !== null) {
				#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:84: characters 20-28
				return $s;
			}
		}

		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:86: characters 3-30
		$ip = $_SERVER["REMOTE_ADDR"];
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:87: characters 3-25
		$s1 = new Session();
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:88: characters 3-12
		$s1->ip = $ip;
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:89: characters 3-28
		$s1->createTime = \Date::now();
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:90: characters 3-26
		$s1->lastTime = \Date::now();
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:92: characters 3-23
		$s1->sid = Session::generateId();
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:93: characters 3-18
		$count = 20;
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:94: lines 94-101
		while (true) {
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:94: characters 10-62
			$tmp = null;
			try {
				#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:94: characters 16-26
				$s1->insert();
				#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:94: characters 10-62
				$tmp = false;
			} catch (\Throwable $__hx__caught_e) {
				CallStack::saveExceptionTrace($__hx__caught_e);
				$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
				$e = $__hx__real_e;
				$tmp = true;
			}
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:94: lines 94-101
			if (!$tmp) {
				break;
			}
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:95: characters 4-24
			$s1->sid = Session::generateId();
			#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:97: lines 97-100
			if ($count-- === 0) {
				#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:98: characters 5-15
				$s1->insert();
				#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:99: characters 5-10
				break;
			}
		}
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:103: characters 3-11
		return $s1;
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:27: characters 3-10
		parent::__construct();
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:28: characters 3-16
		$this->set_messages(new \Array_hx());
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:29: characters 3-12
		$this->data = new HxAnon();
	}

	/**
	 * @return Manager
	 */
	public function __getManager () {
		#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1432: characters 19-40
		return Session::$manager;
	}

	/**
	 * Stores a message in session
	 * 
	 * @param string $text
	 * @param bool $error
	 * 
	 * @return void
	 */
	public function addMessage ($text, $error = false) {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:36: characters 3-48
		if ($error === null) {
			$error = false;
		}
		$_this = $this->get_messages();
		$_this->arr[$_this->length] = new HxAnon([
			"error" => $error,
			"text" => $text,
		]);
		++$_this->length;
	}

	/**
	 * @return \Array_hx
	 */
	public function get_messages () {
		#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1283: characters 20-154
		if ($this->cache_messages === null) {
			#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1283: characters 44-113
			$this->cache_messages = new HxAnon(["v" => Session::$manager->doUnserialize("data_messages", $this->data_messages)]);
			#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1283: characters 115-151
			\Reflect::setField($this, "data_messages", new HxAnon());
		}
		#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1283: characters 156-172
		return $this->cache_messages->v;
	}

	/**
	 * @return User
	 */
	public function get_user () {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:24: characters 18-51
		return User::$manager->__hx__renamed__get($this, "user", "uid", false);
	}

	/**
	 * @param User $u
	 * 
	 * @return void
	 */
	public function setUser ($u) {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:43: characters 3-29
		Session::$manager->unsafeDelete("DELETE FROM Session WHERE " . (Manager::nullCompare("uid", Manager::quoteAny($u->id), true)??'null'));
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:45: characters 3-16
		$this->lang = $u->lang;
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:46: characters 3-11
		$this->set_user($u);
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:47: characters 3-11
		$this->update();
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:49: characters 3-23
		\App::$current->user = $u;
	}

	/**
	 * @param \Array_hx $_v
	 * 
	 * @return \Array_hx
	 */
	public function set_messages ($_v) {
		#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1289: characters 20-106
		if ($this->cache_messages === null) {
			#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1289: characters 44-64
			$this->cache_messages = new HxAnon(["v" => $_v]);
			#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1289: characters 66-83
			$this->data_messages = new HxAnon();
		} else {
			#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1289: characters 92-106
			$this->cache_messages->v = $_v;
		}
		#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1289: characters 108-117
		return $_v;
	}

	/**
	 * @param User $_v
	 * 
	 * @return User
	 */
	public function set_user ($_v) {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:24: characters 18-51
		return User::$manager->__hx__renamed__set($this, "user", "uid", $_v);
	}

	/**
	 * @return void
	 */
	public function update () {
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:56: characters 3-36
		$this->sdata = Serializer::run($this->data);
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:58: characters 3-24
		$this->lastTime = \Date::now();
		#/home/bubar/projects/sugoi/src/sugoi/db/Session.hx:59: characters 3-17
		parent::update();
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$manager = new Manager(Boot::getClass(Session::class));
	}
}

Boot::registerClass(Session::class, 'sugoi.db.Session');
Boot::registerMeta(Session::class, new HxAnon(["obj" => new HxAnon(["rtti" => \Array_hx::wrap(["oy7:hfieldsby3:uidoy4:nameR1y1:tjy17:sys.db.RecordType:1:0y6:isNulltgy3:sidoR2R6R3jR4:9:1i32R5fgy5:sdataoR2R7R3jR4:15:0R5fgy8:messagesoR2R8R3jR4:30:0R5fgy8:lastTimeoR2R9R3jR4:11:0R5fgy4:langoR2R10R3jR4:9:1i2R5fgy2:ipoR2R11R3jR4:9:1i15R5fgy10:createTimeoR2R12R3r11R5fghR2y7:Sessiony9:relationsaoy6:moduley7:db.Usery7:cascadefy4:lockfy4:propy4:userR5ty4:typeR16y3:keyR1ghy7:indexesaoy4:keysaR1hy6:uniquetghy6:fieldsar4r14r12r8r10r16r6r2hR22aR6hg"])])]));
Boot::registerGetters('sugoi\\db\\Session', [
	'user' => true,
	'messages' => true
]);
Boot::registerSetters('sugoi\\db\\Session', [
	'user' => true,
	'messages' => true
]);
Session::__hx__init();
