<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace tink\core;

use \php\Boot;
use \haxe\ds\ObjectMap;
use \haxe\IMap;

class Annex {
	/**
	 * @var IMap
	 */
	public $registry;
	/**
	 * @var mixed
	 */
	public $target;

	/**
	 * @param mixed $target
	 * 
	 * @return void
	 */
	public function __construct ($target) {
		#/home/bubar/haxe/haxe_libraries/tink_core/1.21.0/haxelib/src/tink/core/Annex.hx:16: characters 4-24
		$this->target = $target;
		#/home/bubar/haxe/haxe_libraries/tink_core/1.21.0/haxelib/src/tink/core/Annex.hx:17: characters 5-49
		$this->registry = new ObjectMap();
	}
}

Boot::registerClass(Annex::class, 'tink.core.Annex');
