<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace db;

use \php\_Boot\HxAnon;
use \php\Boot;
use \sys\db\Object_hx;
use \sys\db\Manager;
use \haxe\ds\StringMap;

class Chapitre extends Object_hx {
	/**
	 * @var Manager
	 */
	static public $manager;

	/**
	 * @var string
	 */
	public $description;
	/**
	 * @var int
	 */
	public $id;
	/**
	 * @var int
	 */
	public $order;
	/**
	 * @var Questionnaire
	 */
	public $questionnaire;
	/**
	 * @var mixed
	 */
	public $questionnaireId;
	/**
	 * @var string
	 */
	public $title;

	/**
	 * @return StringMap
	 */
	static public function getLabels () {
		#src/db/Chapitre.hx:26: lines 26-30
		$_g = new StringMap();
		$_g->data["title"] = "Titre";
		$_g->data["description"] = "Description";
		$_g->data["order"] = "Ordre";
		return $_g;
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#src/db/Chapitre.hx:16: characters 9-16
		parent::__construct();
	}

	/**
	 * @return Manager
	 */
	public function __getManager () {
		#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1432: characters 19-40
		return Chapitre::$manager;
	}

	/**
	 * @return \Array_hx
	 */
	public function getPages () {
		#src/db/Chapitre.hx:21: characters 9-91
		return \Lambda::array(Page::$manager->unsafeObjects("SELECT * FROM Page WHERE chapitreId = " . (Manager::quoteAny(Chapitre::$manager->unsafeGetId($this))??'null') . " ORDER BY `order`", false));
	}

	/**
	 * @return Questionnaire
	 */
	public function get_questionnaire () {
		#src/db/Chapitre.hx:12: characters 48-92
		return Questionnaire::$manager->__hx__renamed__get($this, "questionnaire", "questionnaireId", false);
	}

	/**
	 * @param Questionnaire $_v
	 * 
	 * @return Questionnaire
	 */
	public function set_questionnaire ($_v) {
		return Questionnaire::$manager->__hx__renamed__set($this, "questionnaire", "questionnaireId", $_v);
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$manager = new Manager(Boot::getClass(Chapitre::class));
	}
}

Boot::registerClass(Chapitre::class, 'db.Chapitre');
Boot::registerMeta(Chapitre::class, new HxAnon([
	"obj" => new HxAnon(["rtti" => \Array_hx::wrap(["oy7:hfieldsby5:titleoy4:nameR1y1:tjy17:sys.db.RecordType:9:1i256y6:isNullfgy15:questionnaireIdoR2R6R3jR4:1:0R5fgy5:orderoR2R7R3r5R5fgy2:idoR2R8R3jR4:0:0R5fgy11:descriptionoR2R9R3jR4:15:0R5fghR2y8:Chapitrey9:relationsaoy6:moduley16:db.Questionnairey7:cascadefy4:lockfy4:propy13:questionnaireR5fy4:typeR13y3:keyR6ghy7:indexesahy6:fieldsar7r2r9r6r4hR19aR8hg"])]),
	"fields" => new HxAnon(["questionnaire" => new HxAnon(["hideInForms" => null])]),
]));
Boot::registerGetters('db\\Chapitre', [
	'questionnaire' => true
]);
Boot::registerSetters('db\\Chapitre', [
	'questionnaire' => true
]);
Chapitre::__hx__init();
