<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace db;

use \php\_Boot\HxAnon;
use \php\Boot;
use \sys\db\Object_hx;
use \sys\db\Manager;

class Identifier extends Object_hx {
	/**
	 * @var Manager
	 */
	static public $manager;

	/**
	 * @var string
	 */
	public $activite;
	/**
	 * @var string
	 */
	public $activite_agricole;
	/**
	 * @var string
	 */
	public $elements;
	/**
	 * @var string
	 */
	public $email;
	/**
	 * @var int
	 */
	public $id;
	/**
	 * @var string
	 */
	public $localisation;
	/**
	 * @var string
	 */
	public $nom;
	/**
	 * @var string
	 */
	public $phone;
	/**
	 * @var string
	 */
	public $responsables;
	/**
	 * @var Result
	 */
	public $result;
	/**
	 * @var mixed
	 */
	public $resultId;
	/**
	 * @var User
	 */
	public $user;
	/**
	 * @var mixed
	 */
	public $userId;

	/**
	 * @param User $user
	 * 
	 * @return Identifier
	 */
	static public function getOrCreate ($user) {
		#src/db/Identifier.hx:23: characters 9-50
		$x = Identifier::$manager->unsafeObjects("SELECT * FROM Identifier WHERE userId = " . (Manager::quoteAny(User::$manager->unsafeGetId($user))??'null'), true)->first();
		#src/db/Identifier.hx:24: lines 24-28
		if ($x === null) {
			#src/db/Identifier.hx:25: characters 13-33
			$x = new Identifier();
			#src/db/Identifier.hx:26: characters 13-26
			$x->set_user($user);
			#src/db/Identifier.hx:27: characters 13-23
			$x->insert();
		}
		#src/db/Identifier.hx:29: characters 9-17
		return $x;
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#src/db/Identifier.hx:5: lines 5-32
		parent::__construct();
	}

	/**
	 * @return Manager
	 */
	public function __getManager () {
		#/home/bubar/projects/spod/src/sys/db/RecordMacros.hx:1432: characters 19-40
		return Identifier::$manager;
	}

	/**
	 * @return Result
	 */
	public function get_result () {
		#src/db/Identifier.hx:9: characters 26-63
		return Result::$manager->__hx__renamed__get($this, "result", "resultId", false);
	}

	/**
	 * @return User
	 */
	public function get_user () {
		#src/db/Identifier.hx:8: characters 24-50
		return User::$manager->__hx__renamed__get($this, "user", "userId", false);
	}

	/**
	 * @param Result $_v
	 * 
	 * @return Result
	 */
	public function set_result ($_v) {
		#src/db/Identifier.hx:9: characters 26-63
		return Result::$manager->__hx__renamed__set($this, "result", "resultId", $_v);
	}

	/**
	 * @param User $_v
	 * 
	 * @return User
	 */
	public function set_user ($_v) {
		#src/db/Identifier.hx:8: characters 24-50
		return User::$manager->__hx__renamed__set($this, "user", "userId", $_v);
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$manager = new Manager(Boot::getClass(Identifier::class));
	}
}

Boot::registerClass(Identifier::class, 'db.Identifier');
Boot::registerMeta(Identifier::class, new HxAnon(["obj" => new HxAnon(["rtti" => \Array_hx::wrap(["oy7:hfieldsby6:userIdoy4:nameR1y1:tjy17:sys.db.RecordType:1:0y6:isNullfgy8:resultIdoR2R6R3r3R5tgy12:responsablesoR2R7R3jR4:9:1i64R5tgy5:phoneoR2R8R3jR4:9:1i64R5tgy3:nomoR2R9R3jR4:9:1i64R5fgy12:localisationoR2R10R3jR4:9:1i64R5tgy2:idoR2R11R3jR4:0:0R5fgy5:emailoR2R12R3jR4:9:1i64R5tgy8:elementsoR2R13R3jR4:15:0R5tgy17:activite_agricoleoR2R14R3r18R5tgy8:activiteoR2R15R3r18R5tghR2y10:Identifiery9:relationsaoy6:moduley7:db.Usery7:cascadefy4:lockfy4:propy4:userR5fy4:typeR19y3:keyR1goR18y9:db.ResultR20fR21fR22y6:resultR5tR24R26R25R6ghy7:indexesahy6:fieldsar13r9r11r5r15r7r17r20r19r2r4hR25aR11hg"])])]));
Boot::registerGetters('db\\Identifier', [
	'result' => true,
	'user' => true
]);
Boot::registerSetters('db\\Identifier', [
	'result' => true,
	'user' => true
]);
Identifier::__hx__init();
