<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace sys\db;

use \php\Boot;
use \sys\db\_Mysql\MysqlConnection;

class Mysql {
	/**
	 * @param object $params
	 * 
	 * @return Connection
	 */
	static public function connect ($params) {
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/sys/db/Mysql.hx:40: characters 3-37
		return new MysqlConnection($params);
	}
}

Boot::registerClass(Mysql::class, 'sys.db.Mysql');
