<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

namespace controller;

use \php\_Boot\HxAnon;
use \db\Chapitre as DbChapitre;
use \php\Boot;
use \db\Questionnaire as DbQuestionnaire;
use \sys\db\Manager;
use \sugoi\BaseController;
use \php\_Boot\HxException;
use \sugoi\form\Form;

class Chapitre extends BaseController {

	/**
	 * @return void
	 */
	public function __construct () {
		#src/controller/Chapitre.hx:10: characters 3-10
		parent::__construct();
	}

	/**
	 * Modifier un chapitre
	 * 
	 * @param DbChapitre $chapitre
	 * 
	 * @return void
	 */
	public function doEdit ($chapitre) {
		#src/controller/Chapitre.hx:19: characters 9-52
		$f = Form::fromSpod($chapitre);
		#src/controller/Chapitre.hx:21: lines 21-26
		if ($f->isValid()) {
			#src/controller/Chapitre.hx:22: characters 13-28
			$chapitre->lock();
			#src/controller/Chapitre.hx:23: characters 13-31
			$f->toSpod($chapitre);
			#src/controller/Chapitre.hx:24: characters 13-30
			$chapitre->update();
			#src/controller/Chapitre.hx:25: characters 13-18
			throw new HxException($this->Ok("/questionnaire/view/" . ($chapitre->get_questionnaire()->id??'null'), "Chapitre mis à jour"));
		}
		#src/controller/Chapitre.hx:28: characters 9-22
		$this->view->form = $f;
	}

	/**
	 * Ajouter un chapitre à un questionnaire
	 * 
	 * @param DbQuestionnaire $questionnaire
	 * 
	 * @return void
	 */
	public function doInsert ($questionnaire) {
		#src/controller/Chapitre.hx:36: characters 9-42
		$chapitre = new DbChapitre();
		#src/controller/Chapitre.hx:37: characters 9-82
		$chapitre->order = DbChapitre::$manager->unsafeCount("SELECT COUNT(*) FROM Chapitre WHERE questionnaireId = " . (Manager::quoteAny(DbQuestionnaire::$manager->unsafeGetId($questionnaire))??'null'));
		#src/controller/Chapitre.hx:38: characters 9-54
		$f = Form::fromSpod($chapitre);
		#src/controller/Chapitre.hx:39: lines 39-45
		if ($f->isValid()) {
			#src/controller/Chapitre.hx:40: characters 13-31
			$f->toSpod($chapitre);
			#src/controller/Chapitre.hx:41: characters 13-51
			$chapitre->set_questionnaire($questionnaire);
			#src/controller/Chapitre.hx:42: characters 13-30
			$chapitre->insert();
			#src/controller/Chapitre.hx:43: characters 13-18
			throw new HxException($this->Ok("/questionnaire/view/" . ($questionnaire->id??'null'), "Nouveau chapitre créé"));
		}
		#src/controller/Chapitre.hx:47: characters 9-22
		$this->view->form = $f;
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


	}
}

Boot::registerClass(Chapitre::class, 'controller.Chapitre');
Boot::registerMeta(Chapitre::class, new HxAnon([
	"obj" => new HxAnon(["dispatchConfig" => \Array_hx::wrap(["oy4:editjy21:haxe.web.DispatchRule:3:1jR1:0:1jy18:haxe.web.MatchRule:7:2y11:db.Chapitrefy6:insertjR1:3:1jR1:0:1jR2:7:2y16:db.Questionnairefy4:filejR1:0:1jR2:3:0g"])]),
	"fields" => new HxAnon([
		"doEdit" => new HxAnon([
			"admin" => null,
			"tpl" => \Array_hx::wrap(["form.twig"]),
		]),
		"doInsert" => new HxAnon([
			"admin" => null,
			"tpl" => \Array_hx::wrap(["form.twig"]),
		]),
	]),
]));
Chapitre::__hx__init();
