<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

use \php\_Boot\HxAnon;
use \sugoi\Config;
use \sugoi\BaseApp;
use \php\Boot;
use \sugoi\mail\IMailer;
use \sugoi\i18n\GetText;
use \sugoi\mail\MandrillMailer;

class App extends BaseApp {
	/**
	 * @var Config
	 */
	static public $config;
	/**
	 * @var App
	 */
	static public $current = null;
	/**
	 * @var GetText
	 */
	static public $t;

	/**
	 * @return IMailer
	 */
	static public function getMailer () {
		#src/App.hx:34: characters 14-41
		$conf = App::$config->get("smtp_host");
		#src/App.hx:35: characters 14-55
		$conf1 = \Std::parseInt(App::$config->get("smtp_port"));
		#src/App.hx:36: characters 14-41
		$conf2 = App::$config->get("smtp_user");
		#src/App.hx:33: lines 33-38
		$conf3 = new HxAnon([
			"smtp_host" => $conf,
			"smtp_port" => $conf1,
			"smtp_user" => $conf2,
			"smtp_pass" => App::$config->get("smtp_pass"),
		]);
		#src/App.hx:41: characters 3-52
		return (new MandrillMailer())->init($conf3);
	}

	/**
	 * @param mixed $t
	 * 
	 * @return void
	 */
	static public function log ($t) {
		#src/App.hx:18: characters 6-22
		$tmp = App::$config->DEBUG;
	}

	/**
	 * @return void
	 */
	static public function main () {
		#src/App.hx:12: characters 3-23
		BaseApp::main();
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#src/App.hx:3: lines 3-80
		parent::__construct();
	}

	/**
	 * process a template and returns the generated string
	 * @param	tpl
	 * @param	ctx
	 * 
	 * @param string $tpl
	 * @param mixed $ctx
	 * 
	 * @return string
	 */
	public function processTemplate ($tpl, $ctx) {
		#src/App.hx:75: characters 3-12
		return "";
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$config = BaseApp::$config;
	}
}

Boot::registerClass(App::class, 'App');
App::__hx__init();
