<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

use \php\Boot;
use \php\_Boot\HxException;

final /**
 * The EReg class represents regular expressions.
 * While basic usage and patterns consistently work across platforms, some more
 * complex operations may yield different results. This is a necessary trade-
 * off to retain a certain level of performance.
 * EReg instances can be created by calling the constructor, or with the
 * special syntax `~/pattern/modifier`
 * EReg instances maintain an internal state, which is affected by several of
 * its methods.
 * A detailed explanation of the supported operations is available at
 * <https://haxe.org/manual/std-regex.html>
 */
class EReg {
	/**
	 * @var bool
	 */
	public $global;
	/**
	 * @var string
	 */
	public $last;
	/**
	 * @var mixed
	 */
	public $matches;
	/**
	 * @var string
	 */
	public $options;
	/**
	 * @var string
	 */
	public $pattern;
	/**
	 * @var string
	 */
	public $re;

	/**
	 * Creates a new regular expression with pattern `r` and modifiers `opt`.
	 * This is equivalent to the shorthand syntax `~/r/opt`
	 * If `r` or `opt` are null, the result is unspecified.
	 * 
	 * @param string $r
	 * @param string $opt
	 * 
	 * @return void
	 */
	public function __construct ($r, $opt) {
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:37: characters 3-19
		$this->pattern = $r;
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:38: characters 3-45
		$this->options = str_replace("g", "", $opt);
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:39: characters 3-26
		$this->global = $this->options !== $opt;
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:40: characters 3-69
		$this->re = "\"" . (str_replace("\"", "\\\"", $r)??'null') . "\"u" . ($this->options??'null');
	}

	/**
	 * Tells if `this` regular expression matches String `s`.
	 * This method modifies the internal state.
	 * If `s` is `null`, the result is unspecified.
	 * 
	 * @param string $s
	 * 
	 * @return bool
	 */
	public function match ($s) {
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:44: characters 3-78
		$p = preg_match($this->re, $s, $this->matches, PREG_OFFSET_CAPTURE);
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:46: lines 46-50
		if ($p > 0) {
			#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:47: characters 4-12
			$this->last = $s;
		} else {
			#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:49: characters 4-15
			$this->last = null;
		}
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:51: characters 3-15
		return $p > 0;
	}

	/**
	 * Returns the matched sub-group `n` of `this` EReg.
	 * This method should only be called after `this.match` or
	 * `this.matchSub`, and then operates on the String of that operation.
	 * The index `n` corresponds to the n-th set of parentheses in the pattern
	 * of `this` EReg. If no such sub-group exists, the result is unspecified.
	 * If `n` equals 0, the whole matched substring is returned.
	 * 
	 * @param int $n
	 * 
	 * @return string
	 */
	public function matched ($n) {
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:55: characters 3-39
		if (($this->matches === null) || ($n < 0)) {
			#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:55: characters 34-39
			throw new HxException("EReg::matched");
		}
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:58: characters 3-46
		if ($n >= count($this->matches)) {
			#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:58: characters 35-46
			return null;
		}
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:59: characters 3-43
		if ($this->matches[$n][1] < 0) {
			#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:59: characters 32-43
			return null;
		}
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:60: characters 3-23
		return $this->matches[$n][0];
	}

	/**
	 * Replaces the first substring of `s` which `this` EReg matches with `by`.
	 * If `this` EReg does not match any substring, the result is `s`.
	 * By default, this method replaces only the first matched substring. If
	 * the global g modifier is in place, all matched substrings are replaced.
	 * If `by` contains `$1` to `$9`, the digit corresponds to number of a
	 * matched sub-group and its value is used instead. If no such sub-group
	 * exists, the replacement is unspecified. The string `$$` becomes `$`.
	 * If `s` or `by` are null, the result is unspecified.
	 * 
	 * @param string $s
	 * @param string $by
	 * 
	 * @return string
	 */
	public function replace ($s, $by) {
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:99: characters 3-46
		$by = str_replace("\\\$", "\\\\\$", $by);
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:100: characters 3-43
		$by = str_replace("\$\$", "\\\$", $by);
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:101: lines 101-103
		if (!preg_match("/\\\\([^?].*?\\\\)/", $this->re)) {
			#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:102: characters 4-57
			$by = preg_replace("/\\\$(\\d+)/", "\\\$\\1", $by);
		}
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/EReg.hx:104: characters 3-57
		return preg_replace($this->re, $by, $s, ($this->global ? -1 : 1));
	}
}

Boot::registerClass(EReg::class, 'EReg');
