<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 */

use \php\Boot;
use \php\_Boot\HxString;

/**
 * This class gives you access to many base functionalities of system platforms. Looks in `sys` sub packages for more system APIs.
 */
class Sys {
	/**
	 * Returns the name of the system you are running on. For instance :
	 * "Windows", "Linux", "BSD" and "Mac" depending on your desktop OS.
	 * 
	 * @return string
	 */
	static public function systemName () {
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/Sys.hx:77: characters 3-33
		$s = php_uname("s");
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/Sys.hx:78: characters 3-26
		$p = HxString::indexOf($s, " ");
		#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/Sys.hx:79: characters 10-39
		if ($p >= 0) {
			#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/Sys.hx:79: characters 20-34
			return mb_substr($s, 0, $p);
		} else {
			#/home/bubar/haxe/versions/4.0.0-rc.1/std/php/_std/Sys.hx:79: characters 37-38
			return $s;
		}
	}
}

Boot::registerClass(Sys::class, 'Sys');
